name: flutter_native_runtime_showcase
description: Monaco and TradingView showcase for WebScene.Backend.Flutter.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webscene_flutter:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
