import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseAll } from "@webref/idl";

const toolDirectory = dirname(fileURLToPath(import.meta.url));
const manifestPath = resolve(toolDirectory, "dom-exposure.json");
const outputPath = resolve(
  toolDirectory,
  "../../experiments/WebScene.NativeEngine.Probe/native/generated/webscene_dom_bindings.inc");
const checkOnly = process.argv.includes("--check");

const manifestText = await readFile(manifestPath, "utf8");
const manifest = JSON.parse(manifestText);
if (manifest.schemaVersion !== 1 || !Array.isArray(manifest.interfaces)) {
  throw new Error("Unsupported or malformed WebScene DOM exposure manifest");
}

const webref = await parseAll();
const definitions = Object.values(webref).flat();
const standardMembers = new Set();
const standardInterfaces = new Map();
for (const definition of definitions) {
  if (definition.name && Array.isArray(definition.members)) {
    const current = standardInterfaces.get(definition.name) ?? [];
    current.push(definition);
    standardInterfaces.set(definition.name, current);
    for (const member of definition.members) {
      if (member.name) standardMembers.add(member.name);
    }
  }
}

const byName = new Map(manifest.interfaces.map(value => [value.name, value]));
for (const value of manifest.interfaces) {
  if (!standardInterfaces.has(value.name)) {
    throw new Error(`WebRef does not define interface ${value.name}`);
  }
  if (value.parent && !byName.has(value.parent)) {
    throw new Error(`${value.name} refers to missing parent ${value.parent}`);
  }
  for (const member of [...value.attributes, ...value.methods]) {
    if (!member.extension && !standardMembers.has(member.name)) {
      throw new Error(`WebRef does not define exposed member ${member.name}`);
    }
  }
}

const safe = value => value.replace(/[^A-Za-z0-9_]/g, "_");
const lines = [];
const line = (value = "") => lines.push(value);
const manifestHash = createHash("sha256").update(manifestText).digest("hex");

line("// Generated by tools/webidl-v8-bindings/generate.mjs. Do not edit.");
line(`// Exposure manifest SHA-256: ${manifestHash}`);
line("// Inputs: @webref/idl 3.82.1, webidl2 24.5.0.");
line();
line("enum class generated_dom_interface : uint8_t {");
for (const value of manifest.interfaces) line(`    ${safe(value.name)},`);
line("};");
line();
line("static void throw_generated_illegal_invocation(v8::Isolate* isolate)");
line("{");
line("    isolate->ThrowException(v8::Exception::TypeError(");
line("        js_string(isolate, \"Illegal invocation\")));");
line("}");
line();
line("static void event_target_constructor(");
line("    const v8::FunctionCallbackInfo<v8::Value>& info)");
line("{");
line("    if (!info.IsConstructCall()) {");
line("        info.GetIsolate()->ThrowException(v8::Exception::TypeError(");
line("            js_string(info.GetIsolate(),");
line("                \"Failed to construct 'EventTarget': Please use the 'new' operator\")));");
line("        return;");
line("    }");
line("    auto* self = current(info.GetIsolate());");
line("    if (self == nullptr) return;");
line("    info.This()->SetAlignedPointerInInternalField(");
line("        0, nullptr, v8::kEmbedderDataTypeTagDefault);");
line("    info.This()->SetInternalField(");
line("        1, v8::Integer::NewFromUnsigned(");
line("            info.GetIsolate(), self->next_standalone_event_target_id++));");
line("    info.GetReturnValue().Set(info.This());");
line("}");
line();
line("static void illegal_dom_constructor(");
line("    const v8::FunctionCallbackInfo<v8::Value>& info)");
line("{");
line("    info.GetIsolate()->ThrowException(v8::Exception::TypeError(");
line("        js_string(info.GetIsolate(), \"Illegal constructor\")));");
line("}");
line();
line("static bool generated_dom_receiver_is(");
line("    v8::Isolate* isolate,");
line("    v8::Local<v8::Value> receiver,");
line("    generated_dom_interface interface_kind)");
line("{");
line("    auto* self = current(isolate);");
line("    if (self == nullptr || receiver.IsEmpty()) return false;");
line("    switch (interface_kind) {");
for (const value of manifest.interfaces) {
  line(`    case generated_dom_interface::${safe(value.name)}:`);
  line(`        return !self->${value.template}.IsEmpty()`);
  line(`            && self->${value.template}.Get(isolate)->HasInstance(receiver);`);
}
line("    }");
line("    return false;");
line("}");
line();
line("static std::optional<uint32_t> generated_standalone_event_target_id(");
line("    v8::Isolate* isolate,");
line("    v8::Local<v8::Object> receiver)");
line("{");
line("    if (receiver.IsEmpty() || receiver->InternalFieldCount() < 2) {");
line("        return std::nullopt;");
line("    }");
line("    auto value = receiver->GetInternalField(1).As<v8::Value>();");
line("    if (!value->IsUint32()) return std::nullopt;");
line("    return value->Uint32Value(isolate->GetCurrentContext()).FromMaybe(0U);");
line("}");
line();

for (const value of manifest.interfaces) {
  for (const attribute of value.attributes) {
    const prefix = `generated_${safe(value.name)}_${safe(attribute.name)}`;
    line(`static void ${prefix}_get(`);
    line("    v8::Local<v8::Name> property,");
    line("    const v8::PropertyCallbackInfo<v8::Value>& info)");
    line("{");
    line(`    if (!generated_dom_receiver_is(info.GetIsolate(), info.Holder(), generated_dom_interface::${safe(value.name)})) {`);
    line("        throw_generated_illegal_invocation(info.GetIsolate());");
    line("        return;");
    line("    }");
    line(`    ${attribute.getter}(property, info);`);
    line("}");
    line();
    if (attribute.setter) {
      line(`static void ${prefix}_set(`);
      line("    v8::Local<v8::Name> property,");
      line("    v8::Local<v8::Value> value,");
      line("    const v8::PropertyCallbackInfo<void>& info)");
      line("{");
      line(`    if (!generated_dom_receiver_is(info.GetIsolate(), info.Holder(), generated_dom_interface::${safe(value.name)})) {`);
      line("        throw_generated_illegal_invocation(info.GetIsolate());");
      line("        return;");
      line("    }");
      line(`    ${attribute.setter}(property, value, info);`);
      line("}");
      line();
    }
  }
}

line("void install_generated_dom_templates(v8::Local<v8::Context>)");
line("{");
for (const value of manifest.interfaces) {
  const local = `generated_${safe(value.name)}_template`;
  line(`    auto ${local} = v8::FunctionTemplate::New(isolate, ${value.constructor});`);
  line(`    ${local}->SetClassName(js_string(isolate, \"${value.name}\"));`);
  line(`    ${local}->SetInterfaceName(js_string(isolate, \"${value.name}\"));`);
  if (value.parent) {
    line(`    ${local}->Inherit(generated_${safe(value.parent)}_template);`);
  }
  line(`    ${local}->InstanceTemplate()->SetInternalFieldCount(2);`);
  for (const attribute of value.attributes) {
    const prefix = `generated_${safe(value.name)}_${safe(attribute.name)}`;
    const setter = attribute.setter ? `${prefix}_set` : "nullptr";
    const propertyAttributes = attribute.attributes?.length
      ? `static_cast<v8::PropertyAttribute>(${attribute.attributes.map(name => `v8::PropertyAttribute::${name}`).join(" | ")})`
      : "v8::PropertyAttribute::None";
    line(`    ${local}->InstanceTemplate()->SetNativeDataProperty(`);
    line(`        js_string(isolate, \"${attribute.name}\"),`);
    line(`        ${prefix}_get,`);
    line(`        ${setter},`);
    line("        v8::Local<v8::Value>(),");
    line(`        ${propertyAttributes});`);
  }
  if (value.methods.length) {
    line(`    auto generated_${safe(value.name)}_signature =`);
    line(`        v8::Signature::New(isolate, ${local});`);
  }
  for (const method of value.methods) {
    line(`    ${local}->PrototypeTemplate()->Set(`);
    line(`        js_string(isolate, \"${method.name}\"),`);
    line("        v8::FunctionTemplate::New(");
    line(`            isolate, ${method.callback}, v8::Local<v8::Value>(),`);
    line(`            generated_${safe(value.name)}_signature, ${method.length},`);
    line("            v8::ConstructorBehavior::kThrow));");
  }
  for (const constant of value.constants) {
    line(`    ${local}->PrototypeTemplate()->Set(`);
    line(`        js_string(isolate, \"${constant.name}\"),`);
    line(`        v8::Integer::New(isolate, ${constant.value}),`);
    line("        static_cast<v8::PropertyAttribute>(");
    line("            v8::PropertyAttribute::ReadOnly");
    line("            | v8::PropertyAttribute::DontDelete));");
  }
  line(`    ${value.template}.Reset(isolate, ${local});`);
  line();
}
line("}");
line();
line("void install_generated_dom_constructors(");
line("    v8::Local<v8::Context> local_context,");
line("    v8::Local<v8::Object> global)");
line("{");
for (const value of manifest.interfaces) {
  line(`    auto generated_${safe(value.name)}_constructor = ${value.template}.Get(isolate)`);
  line("        ->GetFunction(local_context).ToLocalChecked();");
  for (const constant of value.constants) {
    line(`    generated_${safe(value.name)}_constructor->Set(`);
    line(`        local_context, js_string(isolate, \"${constant.name}\"),`);
    line(`        v8::Integer::New(isolate, ${constant.value})).Check();`);
  }
  line(`    global->Set(local_context, js_string(isolate, \"${value.name}\"),`);
  line(`        generated_${safe(value.name)}_constructor).Check();`);
}
for (const [alias, target] of Object.entries(manifest.aliases)) {
  line(`    global->Set(local_context, js_string(isolate, \"${alias}\"),`);
  line(`        generated_${safe(target)}_constructor).Check();`);
}
line("}");

const generated = `${lines.join("\n")}\n`;
if (checkOnly) {
  let existing;
  try {
    existing = await readFile(outputPath, "utf8");
  } catch {
    throw new Error(`Generated binding file is missing: ${outputPath}`);
  }
  if (existing !== generated) {
    throw new Error("Generated WebIDL bindings are stale; run npm run generate");
  }
} else {
  await writeFile(outputPath, generated);
}

console.log(`${checkOnly ? "checked" : "generated"} ${manifest.interfaces.length} interfaces, ${
  manifest.interfaces.reduce((sum, value) => sum + value.attributes.length + value.methods.length, 0)
} members -> ${outputPath}`);
