<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
    <VersionPrefix>1.0.27</VersionPrefix>
    <Authors>Wiesław Šoltés</Authors>
    <Company>Wiesław Šoltés</Company>
    <Copyright>Copyright © Wiesław Šoltés 2025</Copyright>
    <PackageProjectUrl>https://github.com/wieslawsoltes/WebScene</PackageProjectUrl>
    <RepositoryUrl>https://github.com/wieslawsoltes/WebScene</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>webscene-logo.jpg</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <AvaloniaVersion>11.3.4</AvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)LICENSE"
          Pack="true"
          PackagePath=""
          Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)docs\assets\webscene-logo.jpg"
          Pack="true"
          PackagePath="webscene-logo.jpg"
          Visible="false" />
  </ItemGroup>
</Project>
