# Native-only Linux SDK: no V8, runtime HTML loader, or JavaScript payloads.
if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
  message(FATAL_ERROR "The Linux SDK currently targets x86_64")
endif()
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(WEBSCENE_NATIVE_WEB_SDK_BUILD ON)
set(BUILD_TESTING OFF CACHE BOOL "Test installed consumers separately" FORCE)
get_filename_component(WEBSCENE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
find_package(Threads REQUIRED)
option(WEBSCENE_SDK_ENABLE_WEBGPU "Include the pinned Dawn Vulkan backend" ON)
add_subdirectory("${WEBSCENE_ROOT}/src/WebScene.NativeWeb" native-web)
target_link_libraries(webscene-uic PRIVATE Threads::Threads ${CMAKE_DL_LIBS} m)
target_link_libraries(webscene_native_web_shared_css PRIVATE Threads::Threads ${CMAKE_DL_LIBS} m)
add_library(WebScene::Core ALIAS webscene_core)
add_library(WebScene::NativeWeb ALIAS webscene_native_web)
add_library(WebScene::SharedCSS ALIAS webscene_native_web_shared_css)
add_executable(WebScene::Compiler ALIAS webscene-uic)
install(TARGETS webscene_core webscene_native_web webscene_native_web_shared_css ARCHIVE DESTINATION lib)
install(TARGETS webscene-uic RUNTIME DESTINATION bin)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/native-web/parser/release/libwebscene_html_parser.a" DESTINATION lib)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
execute_process(COMMAND "${Python3_EXECUTABLE}" "${WEBSCENE_ROOT}/eng/sdk/header-closure.py" "${WEBSCENE_ROOT}"
  OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake" COMMAND_ERROR_IS_FATAL ANY)
include("${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake")
if(WEBSCENE_SDK_ENABLE_WEBGPU)
  set(WEBSCENE_GRAPHICS_COMPONENTS dawn)
  include("${WEBSCENE_ROOT}/eng/graphics/GraphicsDependencies.cmake")
  install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/include/" DESTINATION include)
  install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/lib/libwebgpu_dawn.so" DESTINATION lib)
  install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/licenses/" DESTINATION share/licenses/WebScene/Dawn)
  install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/webscene-graphics-package.json"
    "${WEBSCENE_ROOT}/eng/graphics/dependencies.lock.json" DESTINATION share/webscene/dependencies)
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/WebSceneLinuxBuild.cmake"
  "set(WebScene_SDK_COMPILER_ID \"${CMAKE_CXX_COMPILER_ID}\")\nset(WebScene_SDK_COMPILER_VERSION \"${CMAKE_CXX_COMPILER_VERSION}\")\nset(WebScene_SDK_WEBGPU ${WEBSCENE_SDK_ENABLE_WEBGPU})\n")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneLinuxBuild.cmake" DESTINATION lib/cmake/WebScene)
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/cmake/" DESTINATION lib/cmake/WebScene)
include(CMakePackageConfigHelpers)
write_basic_package_version_file("${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake"
  VERSION ${PROJECT_VERSION} COMPATIBILITY SameMinorVersion)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake" DESTINATION lib/cmake/WebScene)
