# Installed Runtime profile only. A native-only SDK retains its own toolchain.
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  message(FATAL_ERROR "The Linux Runtime SDK requires a Linux build host")
endif()
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_CXX_STANDARD 20 CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "" FORCE)
find_program(_ws_runtime_cc NAMES clang-18 REQUIRED)
find_program(_ws_runtime_cxx NAMES clang++-18 REQUIRED)
get_filename_component(_ws_runtime_cc "${_ws_runtime_cc}" REALPATH)
get_filename_component(_ws_runtime_cxx "${_ws_runtime_cxx}" REALPATH)
set(CMAKE_C_COMPILER "${_ws_runtime_cc}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${_ws_runtime_cxx}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_FLAGS_INIT "-stdlib=libstdc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-stdlib=libstdc++")
