include(CMakeFindDependencyMacro)
include("${CMAKE_CURRENT_LIST_DIR}/WebSceneRuntimeProfile.cmake")
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
  message(FATAL_ERROR "This Runtime SDK contains Linux x86_64 binaries")
endif()
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR NOT CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL WebScene_SDK_COMPILER_VERSION)
  message(FATAL_ERROR "Use this Runtime SDK's Clang ${WebScene_SDK_COMPILER_VERSION}/libstdc++ toolchain")
endif()
find_dependency(Threads)
get_filename_component(WebScene_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(_ws_runtime_archive name file)
  if(NOT EXISTS "${WebScene_SDK_ROOT}/lib/${file}")
    message(FATAL_ERROR "Incomplete Runtime SDK: ${file} is missing")
  endif()
  add_library(WebScene::${name} STATIC IMPORTED GLOBAL)
  set_target_properties(WebScene::${name} PROPERTIES
    IMPORTED_LOCATION "${WebScene_SDK_ROOT}/lib/${file}"
    INTERFACE_INCLUDE_DIRECTORIES "${WebScene_SDK_ROOT}/include"
    INTERFACE_COMPILE_FEATURES cxx_std_20
    INTERFACE_COMPILE_OPTIONS "-stdlib=libstdc++"
    INTERFACE_LINK_OPTIONS "-stdlib=libstdc++")
endfunction()
if(NOT TARGET WebScene::Core)
  _ws_runtime_archive(Core libwebscene_core.a)
  _ws_runtime_archive(NativeWeb libwebscene_native_web.a)
  _ws_runtime_archive(_Parser libwebscene_html_parser.a)
  _ws_runtime_archive(SharedCSS libwebscene_native_web_shared_css.a)
  set_property(TARGET WebScene::Core PROPERTY INTERFACE_LINK_LIBRARIES "Threads::Threads;${CMAKE_DL_LIBS}")
  set_property(TARGET WebScene::NativeWeb PROPERTY INTERFACE_LINK_LIBRARIES WebScene::Core)
  set_property(TARGET WebScene::SharedCSS PROPERTY INTERFACE_LINK_LIBRARIES "WebScene::NativeWeb;WebScene::_Parser;Threads::Threads;${CMAKE_DL_LIBS};m")
  add_library(WebScene::_Dawn SHARED IMPORTED GLOBAL)
  set_target_properties(WebScene::_Dawn PROPERTIES IMPORTED_LOCATION "${WebScene_SDK_ROOT}/lib/libwebgpu_dawn.so"
    INTERFACE_INCLUDE_DIRECTORIES "${WebScene_SDK_ROOT}/include")
  add_library(WebScene::WebGPU INTERFACE IMPORTED GLOBAL)
  set_target_properties(WebScene::WebGPU PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${WebScene_SDK_ROOT}/include/graphics"
    INTERFACE_LINK_LIBRARIES "WebScene::Core;WebScene::_Dawn;Threads::Threads;${CMAKE_DL_LIBS}")
  add_executable(WebScene::Compiler IMPORTED GLOBAL)
  set_property(TARGET WebScene::Compiler PROPERTY IMPORTED_LOCATION "${WebScene_SDK_ROOT}/bin/webscene-uic")
endif()
# Defining an optional imported target does not cause native applications to
# link it. Keep JavaScript's dependencies off Core, NativeWeb and SharedCSS.
if(NOT TARGET WebScene::Runtime)
  find_dependency(OpenSSL)
  find_dependency(ZLIB)
  _ws_runtime_archive(_V8 libv8_monolith.a)
  _ws_runtime_archive(_WebSocket libixwebsocket.a)
  _ws_runtime_archive(Runtime libwebscene_native_engine.a)
  set(_ws_runtime_libraries WebScene::Core WebScene::_Parser WebScene::_V8 WebScene::_WebSocket
    WebScene::WebGPU OpenSSL::SSL OpenSSL::Crypto ZLIB::ZLIB Threads::Threads ${CMAKE_DL_LIBS} rt m)
  if(WebScene_SDK_MEDIA)
    _ws_runtime_archive(_Media libwebscene_media.a)
    list(APPEND _ws_runtime_libraries WebScene::_Media)
  endif()
  set_property(TARGET WebScene::Runtime PROPERTY INTERFACE_LINK_LIBRARIES "${_ws_runtime_libraries}")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/WebSceneApplication.cmake")
set(WebScene_FOUND TRUE)
unset(WebScene_NOT_FOUND_MESSAGE)
foreach(component IN LISTS WebScene_FIND_COMPONENTS)
  if(TARGET WebScene::${component})
    set(WebScene_${component}_FOUND TRUE)
  else()
    set(WebScene_${component}_FOUND FALSE)
    if(WebScene_FIND_REQUIRED_${component})
      set(WebScene_FOUND FALSE)
      string(APPEND WebScene_NOT_FOUND_MESSAGE "Missing component ${component}. ")
    endif()
  endif()
endforeach()
