# Native-only Linux producer. The existing macOS Runtime profile is unchanged.
if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
  message(FATAL_ERROR "The Linux SDK profile currently targets x86_64")
endif()
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR NOT CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL "22.1.1")
  message(FATAL_ERROR "Linux SDK production requires the pinned LLVM 22.1.1 toolchain")
endif()
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
option(WEBSCENE_SDK_WEBGPU "Include pinned Dawn/Vulkan native authoring support" ON)
option(WEBSCENE_SDK_RUNTIME "Include the optional JavaScript Runtime component" OFF)
if(WEBSCENE_SDK_RUNTIME)
  message(FATAL_ERROR "This Linux SDK profile is Native-only; Runtime/hybrid is not qualified")
endif()
set(BUILD_TESTING OFF CACHE BOOL "Validate through installed SDK consumers" FORCE)
set(WEBSCENE_NATIVE_WEB_SDK_BUILD ON)
get_filename_component(WEBSCENE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
find_package(Threads REQUIRED)
add_subdirectory("${WEBSCENE_ROOT}/src/WebScene.NativeWeb" native-web)
target_link_libraries(webscene_native_web PUBLIC Threads::Threads ${CMAKE_DL_LIBS})
target_link_libraries(webscene_native_web_shared_css PUBLIC Threads::Threads ${CMAKE_DL_LIBS})
add_library(WebScene::Core ALIAS webscene_core)
add_library(WebScene::NativeWeb ALIAS webscene_native_web)
add_library(WebScene::SharedCSS ALIAS webscene_native_web_shared_css)
add_executable(WebScene::Compiler ALIAS webscene-uic)
set_target_properties(webscene-uic PROPERTIES INSTALL_RPATH "$ORIGIN/../lib")
install(TARGETS webscene_core webscene_native_web webscene_native_web_shared_css ARCHIVE DESTINATION lib)
install(TARGETS webscene-uic RUNTIME DESTINATION bin)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/native-web/parser/release/libwebscene_html_parser.a" DESTINATION lib)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
execute_process(COMMAND "${Python3_EXECUTABLE}" "${WEBSCENE_ROOT}/eng/sdk/header-closure.py" "${WEBSCENE_ROOT}"
  OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake" COMMAND_ERROR_IS_FATAL ANY)
include("${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake")
if(WEBSCENE_SDK_WEBGPU)
  set(WEBSCENE_GRAPHICS_COMPONENTS dawn)
  include("${WEBSCENE_ROOT}/eng/graphics/GraphicsDependencies.cmake")
  add_library(webscene_sdk_webgpu INTERFACE)
  target_include_directories(webscene_sdk_webgpu INTERFACE "${WEBSCENE_ROOT}/experiments/WebScene.NativeEngine.Probe/native/graphics")
  target_link_libraries(webscene_sdk_webgpu INTERFACE webscene_core dawn::webgpu_dawn Threads::Threads)
  add_library(WebScene::WebGPU ALIAS webscene_sdk_webgpu)
  install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/include/" DESTINATION include)
  install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/lib/libwebgpu_dawn.so" DESTINATION lib)
  install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/licenses/" DESTINATION share/licenses/WebScene/Dawn)
  install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/webscene-graphics-package.json"
    "${WEBSCENE_ROOT}/eng/graphics/dependencies.lock.json" DESTINATION share/webscene/dependencies)
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/WebSceneLinuxProfile.cmake"
  "set(WebScene_SDK_PLATFORM Linux)\nset(WebScene_SDK_PROCESSOR x86_64)\nset(WebScene_SDK_WEBGPU ${WEBSCENE_SDK_WEBGPU})\nset(WebScene_SDK_RUNTIME OFF)\n")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneLinuxProfile.cmake" DESTINATION lib/cmake/WebScene)
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/cmake/" DESTINATION lib/cmake/WebScene)
include(CMakePackageConfigHelpers)
write_basic_package_version_file("${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake"
  VERSION ${PROJECT_VERSION} COMPATIBILITY SameMinorVersion)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake" DESTINATION lib/cmake/WebScene)
install(FILES "${WEBSCENE_ROOT}/LICENSE" DESTINATION share/licenses/WebScene)
