# Explicit Runtime profile: the host platform and JavaScript capability are independent.
# Uses the same Linux libstdc++ ABI as the existing V8 producer, not the legacy
# native-only LLVM/libc++ profile. No application source belongs in these libraries.
if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
  message(FATAL_ERROR "Linux Runtime SDK currently targets x86_64")
endif()
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR NOT CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL "18.1.3")
  message(FATAL_ERROR "Linux Runtime SDK requires Clang 18.1.3 / libstdc++")
endif()
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_TESTING OFF CACHE BOOL "Qualification uses installed consumers" FORCE)
set(WEBSCENE_NATIVE_WEB_SDK_BUILD ON)
set(WEBSCENE_NATIVE_ENGINE_STATIC ON CACHE BOOL "" FORCE)
set(WEBSCENE_NATIVE_ENGINE_HEADLESS ON CACHE BOOL "" FORCE)
set(WEBSCENE_NATIVE_ENGINE_ENABLE_GRAPHICS ON CACHE BOOL "" FORCE)
set(WEBSCENE_NATIVE_ENGINE_ENABLE_V8 ON CACHE BOOL "" FORCE)
set(WEBSCENE_V8_POINTER_COMPRESSION ON CACHE BOOL "" FORCE)
set(WEBSCENE_V8_POINTER_COMPRESSION_SHARED_CAGE ON CACHE BOOL "" FORCE)
set(WEBSCENE_V8_OPTIMIZE_FOR_SIZE_DEFAULT ON CACHE BOOL "" FORCE)
set(WEBSCENE_NATIVE_ENGINE_V8_SNAPSHOT bootstrap CACHE STRING "" FORCE)
set(WEBSCENE_COMPILED_APPLICATION_MODULE "" CACHE FILEPATH "SDK excludes application payloads" FORCE)
get_filename_component(WEBSCENE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
find_package(Threads REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(ZLIB REQUIRED)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
if(NOT WEBSCENE_V8_ROOT OR NOT WEBSCENE_V8_OUTPUT_ROOT)
  message(FATAL_ERROR "Set WEBSCENE_V8_ROOT and WEBSCENE_V8_OUTPUT_ROOT to verified 15.3.10 Linux V8 inputs")
endif()
execute_process(COMMAND "${Python3_EXECUTABLE}" "${WEBSCENE_ROOT}/eng/sdk/verify-runtime-v8.py"
  "${WEBSCENE_V8_ROOT}" "${WEBSCENE_V8_OUTPUT_ROOT}"
  OUTPUT_VARIABLE _ws_v8_manifest COMMAND_ERROR_IS_FATAL ANY)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/runtime-v8.json" "${_ws_v8_manifest}")
add_subdirectory("${WEBSCENE_ROOT}/src/WebScene.NativeWeb" native-web)
set(WEBSCENE_GRAPHICS_COMPONENTS dawn)
include("${WEBSCENE_ROOT}/eng/graphics/GraphicsDependencies.cmake")
add_subdirectory("${WEBSCENE_ROOT}/experiments/WebScene.NativeEngine.Probe" runtime)
add_library(WebScene::Core ALIAS webscene_core)
add_library(WebScene::NativeWeb ALIAS webscene_native_web)
add_library(WebScene::SharedCSS ALIAS webscene_native_web_shared_css)
add_library(WebScene::Runtime ALIAS webscene_native_engine)
add_executable(WebScene::Compiler ALIAS webscene-uic)
add_library(webscene_sdk_webgpu INTERFACE)
target_include_directories(webscene_sdk_webgpu INTERFACE
  "${WEBSCENE_ROOT}/experiments/WebScene.NativeEngine.Probe/native/graphics")
target_link_libraries(webscene_sdk_webgpu INTERFACE webscene_core dawn::webgpu_dawn Threads::Threads ${CMAKE_DL_LIBS})
add_library(WebScene::WebGPU ALIAS webscene_sdk_webgpu)
set_target_properties(webscene-uic PROPERTIES INSTALL_RPATH "$ORIGIN/../lib")
foreach(target webscene_core webscene_native_web webscene_native_web_shared_css webscene_native_engine)
  target_compile_options(${target} PRIVATE -ffunction-sections -fdata-sections)
endforeach()
install(TARGETS webscene_core webscene_native_web webscene_native_web_shared_css
  webscene_native_engine ixwebsocket ARCHIVE DESTINATION lib)
if(TARGET webscene_media)
  install(TARGETS webscene_media ARCHIVE DESTINATION lib)
endif()
install(TARGETS webscene-uic RUNTIME DESTINATION bin)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/native-web/parser/release/libwebscene_html_parser.a"
  "${WEBSCENE_V8_OUTPUT_ROOT}/obj/libv8_monolith.a" DESTINATION lib)
install(FILES "${WEBSCENE_V8_OUTPUT_ROOT}/icudtl.dat"
  "${CMAKE_CURRENT_BINARY_DIR}/runtime/webscene_bootstrap_snapshot.bin"
  "${CMAKE_CURRENT_BINARY_DIR}/runtime/webscene_bootstrap_snapshot.meta" DESTINATION share/webscene/runtime)
execute_process(COMMAND "${Python3_EXECUTABLE}" "${WEBSCENE_ROOT}/eng/sdk/header-closure.py" "${WEBSCENE_ROOT}"
  OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake" COMMAND_ERROR_IS_FATAL ANY)
include("${CMAKE_CURRENT_BINARY_DIR}/sdk-headers.cmake")
install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/include/" DESTINATION include)
install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/lib/libwebgpu_dawn.so" DESTINATION lib)
install(DIRECTORY "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/licenses/" DESTINATION share/licenses/WebScene/Dawn)
install(FILES "${WEBSCENE_GRAPHICS_SDK_ROOT}/dawn/webscene-graphics-package.json"
  "${CMAKE_CURRENT_BINARY_DIR}/runtime-v8.json" DESTINATION share/webscene/dependencies)
install(FILES "${WEBSCENE_V8_ROOT}/LICENSE" DESTINATION share/licenses/WebScene RENAME V8-LICENSE)
install(FILES "${WEBSCENE_V8_ROOT}/third_party/icu/LICENSE" DESTINATION share/licenses/WebScene RENAME ICU-LICENSE)
install(FILES "${CMAKE_BINARY_DIR}/_deps/webscene_ixwebsocket-src/LICENSE.txt"
  DESTINATION share/licenses/WebScene RENAME IXWebSocket-LICENSE)
if(EXISTS "${CMAKE_BINARY_DIR}/webscene-miniaudio-LICENSE")
  install(FILES "${CMAKE_BINARY_DIR}/webscene-miniaudio-LICENSE" DESTINATION share/licenses/WebScene)
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/WebSceneRuntimeProfile.cmake"
  "set(WebScene_SDK_RUNTIME ON)\nset(WebScene_SDK_WEBGPU ON)\nset(WebScene_SDK_COMPILER_VERSION 18.1.3)\nset(WebScene_SDK_CXX_ABI libstdc++)\nset(WebScene_SDK_MEDIA ${WEBSCENE_NATIVE_ENGINE_ENABLE_MEDIA})\n")
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/cmake/" DESTINATION lib/cmake/WebScene)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneRuntimeProfile.cmake" DESTINATION lib/cmake/WebScene)
include(CMakePackageConfigHelpers)
write_basic_package_version_file("${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake"
  VERSION ${PROJECT_VERSION} COMPATIBILITY SameMinorVersion)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/WebSceneConfigVersion.cmake" DESTINATION lib/cmake/WebScene)
install(FILES "${WEBSCENE_ROOT}/LICENSE" DESTINATION share/licenses/WebScene)
