# Linux and macOS use the same pinned compiler, but distinct system/ABI profiles.
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  if(NOT WEBSCENE_LLVM_ROOT)
    set(WEBSCENE_LLVM_ROOT "$ENV{WEBSCENE_LLVM_ROOT}" CACHE PATH "Pinned LLVM 22.1.1 installation")
  endif()
  if(NOT EXISTS "${WEBSCENE_LLVM_ROOT}/bin/clang++")
    message(FATAL_ERROR "Set WEBSCENE_LLVM_ROOT to the verified LLVM 22.1.1 Linux installation")
  endif()
  set(CMAKE_C_COMPILER "${WEBSCENE_LLVM_ROOT}/bin/clang" CACHE FILEPATH "")
  set(CMAKE_CXX_COMPILER "${WEBSCENE_LLVM_ROOT}/bin/clang++" CACHE FILEPATH "")
  set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")
  set(CMAKE_CXX_STANDARD 20 CACHE STRING "")
  list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES WEBSCENE_LLVM_ROOT)
  file(GLOB _ws_cxx_dirs "${WEBSCENE_LLVM_ROOT}/lib/*-linux-gnu" "${WEBSCENE_LLVM_ROOT}/lib/*-unknown-linux-gnu")
  list(APPEND _ws_cxx_dirs "${WEBSCENE_LLVM_ROOT}/lib")
  foreach(_ws_dir IN LISTS _ws_cxx_dirs)
    if(EXISTS "${_ws_dir}/libc++.so.1")
      set(CMAKE_BUILD_RPATH "${_ws_dir}" CACHE STRING "Pinned C++ ABI runtime")
      break()
    endif()
  endforeach()
  return()
endif()
# Pass with -DCMAKE_TOOLCHAIN_FILE=<SDK>/lib/cmake/WebScene/WebSceneToolchain.cmake.
# Override WEBSCENE_LLVM_ROOT when LLVM is installed outside Homebrew.
set(WEBSCENE_LLVM_ROOT "/opt/homebrew/opt/llvm" CACHE PATH "LLVM 22.1.1 installation")
set(CMAKE_C_COMPILER "${WEBSCENE_LLVM_ROOT}/bin/clang" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "${WEBSCENE_LLVM_ROOT}/bin/clang++" CACHE FILEPATH "")
set(CMAKE_OBJCXX_COMPILER "${WEBSCENE_LLVM_ROOT}/bin/clang++" CACHE FILEPATH "")
if(NOT CMAKE_OSX_SYSROOT)
  execute_process(COMMAND xcrun --sdk macosx --show-sdk-path OUTPUT_VARIABLE sdk_path
    OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  set(CMAKE_OSX_SYSROOT "${sdk_path}" CACHE PATH "macOS SDK")
endif()
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "")
set(CMAKE_OSX_DEPLOYMENT_TARGET 26.0 CACHE STRING "")
set(CMAKE_CXX_STANDARD 20 CACHE STRING "")
