<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\WebScene.Backend.Avalonia\WebScene.Backend.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
  </ItemGroup>

</Project>
