<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.4" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
    <PackageReference Include="WebScene.Sdk" Version="WEBSCENE_PACKAGE_VERSION" />
    <PackageReference Include="WebScene.Sdk.Avalonia" Version="WEBSCENE_PACKAGE_VERSION" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Component/**/*"
             Link="Component/%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
