<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <IsPackable>True</IsPackable>
    <TrimMode>copyused</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <PropertyGroup>
    <Description>An HTML markup support for Avalonia.</Description>
    <PackageId>HtmlML</PackageId>
    <PackageTags>html;axaml;xaml;markup;avalonia;avaloniaui</PackageTags>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS8981</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/wieslawsoltes/HtmlML</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="AngleSharp.Css" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HtmlML.Backend.Avalonia\HtmlML.Backend.Avalonia.csproj" />
  </ItemGroup>
</Project>
