using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WebScene.JavaScript.Interop.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class JavaScriptBindingGenerator : IIncrementalGenerator
{
    private const string BindingAttribute = "WebScene.JavaScript.Interop.JavaScriptBindingAttribute";
    private const string ConstructorAttribute = "WebScene.JavaScript.Interop.JavaScriptConstructorAttribute";
    private const string MethodAttribute = "WebScene.JavaScript.Interop.JavaScriptMethodAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var bindings = context.SyntaxProvider.ForAttributeWithMetadataName(
            BindingAttribute,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        context.RegisterSourceOutput(
            bindings,
            static (productionContext, binding) => Emit(productionContext, binding));
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol binding)
    {
        if (binding.ContainingType is not null || binding.TypeParameters.Length != 0)
        {
            return;
        }

        var methods = binding.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static method => method.IsPartialDefinition)
            .Select(method => new
            {
                Symbol = method,
                Constructor = Attribute(method, ConstructorAttribute),
                Method = Attribute(method, MethodAttribute)
            })
            .Where(static method => method.Constructor is not null || method.Method is not null)
            .ToArray();

        if (methods.Length == 0)
        {
            return;
        }

        var namespaceName = binding.ContainingNamespace.IsGlobalNamespace
            ? null
            : binding.ContainingNamespace.ToDisplayString();
        var typeName = binding.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        if (namespaceName is not null)
        {
            source.Append("namespace ").Append(namespaceName).AppendLine(";").AppendLine();
        }

        source.Append(GetAccessibility(binding.DeclaredAccessibility))
            .Append(' ');
        if (binding.IsSealed)
        {
            source.Append("sealed ");
        }
        source.Append("partial class ")
            .Append(binding.Name)
            .AppendLine(" : global::System.IAsyncDisposable")
            .AppendLine("{")
            .AppendLine("    private readonly global::WebScene.JavaScript.Interop.IJavaScriptInvoker __webSceneInvoker;")
            .AppendLine("    private readonly global::WebScene.JavaScript.Interop.JavaScriptObjectReference __webSceneReference;")
            .AppendLine()
            .Append("    internal ").Append(binding.Name)
            .AppendLine("(global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker, global::WebScene.JavaScript.Interop.JavaScriptObjectReference reference)")
            .AppendLine("    {")
            .AppendLine("        __webSceneInvoker = invoker;")
            .AppendLine("        __webSceneReference = reference;")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    internal global::WebScene.JavaScript.Interop.JavaScriptObjectReference __WebSceneReference => __webSceneReference;")
            .AppendLine()
            .AppendLine("    public global::System.Threading.Tasks.ValueTask DisposeAsync() => __webSceneInvoker.ReleaseAsync(__webSceneReference);");

        foreach (var method in methods)
        {
            source.AppendLine();
            EmitMethod(source, binding, typeName, method.Symbol, method.Constructor, method.Method);
        }

        source.AppendLine("}");
        context.AddSource(
            $"{Sanitize(binding.ToDisplayString())}.WebSceneInterop.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void EmitMethod(
        StringBuilder source,
        INamedTypeSymbol binding,
        string typeName,
        IMethodSymbol method,
        AttributeData? constructor,
        AttributeData? member)
    {
        source.Append("    ")
            .Append(GetAccessibility(method.DeclaredAccessibility))
            .Append(' ');
        if (method.IsStatic)
        {
            source.Append("static ");
        }
        source.Append("partial async ")
            .Append(method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append(' ')
            .Append(method.Name)
            .Append('(')
            .Append(string.Join(", ", method.Parameters.Select(ParameterDeclaration)))
            .AppendLine(")")
            .AppendLine("    {");

        if (constructor is not null)
        {
            var globalName = (string)constructor.ConstructorArguments[0].Value!;
            var invoker = method.Parameters[0].Name;
            var constructorCancellation = CancellationToken(method.Parameters);
            var constructorArguments = method.Parameters
                .Skip(1)
                .Where(static parameter => !IsCancellationToken(parameter.Type));
            source.Append("        return new ").Append(typeName).Append("(@").Append(invoker)
                .Append(", await @").Append(invoker).Append(".ConstructAsync(")
                .Append(SymbolDisplay.FormatLiteral(globalName, quote: true)).Append(", ")
                .Append(ArgumentArray(constructorArguments)).Append(", ")
                .Append(constructorCancellation).AppendLine(").ConfigureAwait(false));");
            source.AppendLine("    }");
            return;
        }

        var memberName = (string)member!.ConstructorArguments[0].Value!;
        var resultType = GetValueTaskResult(method.ReturnType);
        var returnsValue = resultType is not null;
        var returnsBinding = resultType is not null && IsBinding(resultType);
        var promise = member.ConstructorArguments.Length > 1
                      && (int)member.ConstructorArguments[1].Value! == 1;
        var invocation = !returnsValue
            ? "InvokeVoidAsync"
            : returnsBinding
                ? "InvokeObjectAsync"
                : promise
                    ? $"InvokePromiseAsync<{resultType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>"
                    : $"InvokeAsync<{resultType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>";
        var cancellation = CancellationToken(method.Parameters);
        var arguments = method.Parameters.Where(static parameter =>
            !IsCancellationToken(parameter.Type));
        var call = new StringBuilder("__webSceneInvoker.")
            .Append(invocation)
            .Append("(__webSceneReference, ")
            .Append(SymbolDisplay.FormatLiteral(memberName, quote: true))
            .Append(", ")
            .Append(ArgumentArray(arguments))
            .Append(", ")
            .Append(cancellation)
            .Append(')');

        if (!returnsValue)
        {
            source.Append("        await ").Append(call)
                .AppendLine(".ConfigureAwait(false);");
        }
        else if (returnsBinding)
        {
            source.Append("        return new ")
                .Append(resultType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append("(__webSceneInvoker, await ").Append(call)
                .AppendLine(".ConfigureAwait(false));");
        }
        else
        {
            source.Append("        return (await ").Append(call)
                .AppendLine(".ConfigureAwait(false))!;");
        }
        source.AppendLine("    }");
    }

    private static string ArgumentArray(IEnumerable<IParameterSymbol> parameters)
    {
        var values = parameters.Select(parameter =>
        {
            var value = IsBinding(parameter.Type)
                ? $"@{parameter.Name}.__WebSceneReference"
                : $"@{parameter.Name}";
            return $"global::WebScene.JavaScript.Interop.JavaScriptArgument.From({value})";
        });
        return "new global::WebScene.JavaScript.Interop.JavaScriptArgument[] { " + string.Join(", ", values) + " }";
    }

    private static string ParameterDeclaration(IParameterSymbol parameter)
    {
        var prefix = parameter.RefKind switch
        {
            RefKind.In => "in ",
            RefKind.Out => "out ",
            RefKind.Ref => "ref ",
            _ => parameter.IsParams ? "params " : string.Empty
        };
        return prefix
               + parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
               + " @"
               + parameter.Name;
    }

    private static bool IsBinding(ITypeSymbol type)
        => type.GetAttributes().Any(static attribute =>
            attribute.AttributeClass?.ToDisplayString() == BindingAttribute);

    private static ITypeSymbol? GetValueTaskResult(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named
            || named.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks"
            || named.Name != "ValueTask")
        {
            return null;
        }
        return named.TypeArguments.Length == 1 ? named.TypeArguments[0] : null;
    }

    private static bool IsCancellationToken(ITypeSymbol type)
        => type.ToDisplayString() == "System.Threading.CancellationToken";

    private static string CancellationToken(IEnumerable<IParameterSymbol> parameters)
    {
        var parameter = parameters.LastOrDefault(static candidate =>
            IsCancellationToken(candidate.Type));
        return parameter is null
            ? "global::System.Threading.CancellationToken.None"
            : $"@{parameter.Name}";
    }

    private static AttributeData? Attribute(IMethodSymbol method, string name)
        => method.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.ToDisplayString() == name);

    private static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal"
    };

    private static string Sanitize(string name)
        => new(name.Select(static character =>
            char.IsLetterOrDigit(character) ? character : '_').ToArray());
}
