using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace WebScene.JavaScript.Interop.Generator;

public sealed partial class ManifestJavaScriptBindingGenerator
{
    private static string GenerateGlobalFunctions(
        GenerationContext generation,
        string className,
        IReadOnlyList<GlobalFunction> functions,
        IReadOnlyList<GlobalProperty> properties)
    {
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        source.Append("namespace ").Append(generation.Namespace).AppendLine(";")
            .AppendLine()
            .Append("public static class ").Append(className).AppendLine()
            .AppendLine("{");
        foreach (var function in functions)
        {
            EmitGlobalFunction(source, generation, function);
        }
        foreach (var property in properties)
        {
            EmitGlobalProperty(source, generation, property);
        }
        return source.AppendLine("}").ToString();
    }

    private static void EmitGlobalProperty(
        StringBuilder source,
        GenerationContext generation,
        GlobalProperty property)
    {
        var declaredType = property.Property.GetProperty("type");
        var promise = IsPromiseLikeReturn(declaredType);
        var effectiveType = Kind(declaredType) == "promise"
            ? declaredType.GetProperty("result")
            : declaredType;
        var mapping = MapType(
            generation,
            effectiveType,
            optional: false,
            property.Name);
        var valueInvocation = promise
            ? "GetGlobalPromiseAsync"
            : "GetGlobalAsync";
        var objectInvocation = promise
            ? "GetGlobalPromiseObjectAsync"
            : "GetGlobalObjectAsync";
        var binarySupported = CanEmitBinaryType(generation, effectiveType);
        var binaryName = "__WebSceneBinary"
                         + PascalCase(property.Name)
                         + "Global";
        source.AppendLine()
            .Append("    public static ");
        if (!binarySupported)
        {
            source.Append("async ");
        }
        source.Append("global::System.Threading.Tasks.ValueTask<")
            .Append(mapping.CSharpType).Append("> ").Append(property.Name).AppendLine("(")
            .AppendLine("        global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker,")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {")
            .AppendLine("        global::System.ArgumentNullException.ThrowIfNull(invoker);");
        if (binarySupported)
        {
            source.AppendLine("        var binaryInvoker = invoker as global::WebScene.JavaScript.Interop.IJavaScriptBinaryInvoker")
                .AppendLine("            ?? throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        if (!binaryInvoker.IsBinaryInteropAvailable)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        }")
                .Append("        return binaryInvoker.InvokeBinaryAsync<global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid, ")
                .Append(mapping.CSharpType).Append(", ").Append(binaryName)
                .Append("Codec>(").Append(binaryName)
                .AppendLine("CallSite, default, new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid(), cancellationToken);")
                .AppendLine("    }");
            EmitBinaryGlobalPropertyCodec(
                source,
                generation,
                effectiveType,
                mapping,
                binaryName,
                property.GlobalName,
                promise);
            return;
        }
        if (mapping.IsBinding && mapping.IsNullable)
        {
            source.Append("        var reference = await invoker.")
                .Append(valueInvocation)
                .Append("<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append(Literal(property.GlobalName))
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .Append("        return reference is { } value ? new ")
                .Append(mapping.NonNullableCSharpType)
                .AppendLine("(invoker, value) : null;");
        }
        else if (mapping.IsBinding)
        {
            source.Append("        return new ").Append(mapping.CSharpType)
                .Append("(invoker, await invoker.").Append(objectInvocation).Append('(')
                .Append(Literal(property.GlobalName))
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (mapping.IsFunctionReference && mapping.IsNullable)
        {
            source.Append("        var reference = await invoker.")
                .Append(valueInvocation)
                .Append("<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append(Literal(property.GlobalName))
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .AppendLine("        return reference is { } value")
                .AppendLine("            ? new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(invoker, value)")
                .AppendLine("            : null;");
        }
        else if (mapping.IsFunctionReference)
        {
            source.Append("        return new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(invoker, await invoker.")
                .Append(objectInvocation).Append('(')
                .Append(Literal(property.GlobalName))
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (mapping.IsObjectReference && !mapping.IsNullable)
        {
            source.Append("        return await invoker.").Append(objectInvocation).Append('(')
                .Append(Literal(property.GlobalName))
                .AppendLine(", cancellationToken).ConfigureAwait(false);");
        }
        else if (mapping.RequiresWireConversion)
        {
            source.Append("        var wire = (await invoker.")
                .Append(valueInvocation).Append('<')
                .Append(mapping.EffectiveWireCSharpType).Append(">(")
                .Append(Literal(property.GlobalName))
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;")
                .Append("        return ")
                .Append(mapping.ConvertFromWire("wire", "invoker"))
                .AppendLine(";");
        }
        else
        {
            source.Append("        return (await invoker.").Append(valueInvocation).Append('<')
                .Append(mapping.CSharpType).Append(">(")
                .Append(Literal(property.GlobalName))
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;");
        }
        source.AppendLine("    }");
    }

    private static void EmitBinaryGlobalPropertyCodec(
        StringBuilder source,
        GenerationContext generation,
        JsonElement effectiveType,
        TypeMapping mapping,
        string binaryName,
        string globalName,
        bool promise)
    {
        var resultMode = mapping.IsBinding
                         || mapping.IsObjectReference
                         || mapping.IsFunctionReference
            ? "RetainedHandle"
            : "Value";
        source.AppendLine()
            .Append("    private static readonly global::WebScene.JavaScript.Interop.JavaScriptBinaryCallSite ")
            .Append(binaryName).AppendLine("CallSite = new(")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryOperation.GetGlobal,")
            .Append("        globalName: ").Append(Literal(globalName))
            .AppendLine(",")
            .AppendLine("        memberName: null,")
            .Append("        global::WebScene.JavaScript.Interop.JavaScriptBinaryResultMode.")
            .Append(resultMode);
        if (promise)
        {
            source.AppendLine(",")
                .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryCallFlags.AwaitPromise);");
        }
        else
        {
            source.AppendLine(");");
        }
        source.AppendLine()
            .Append("    private readonly struct ").Append(binaryName)
            .Append("Codec : global::WebScene.JavaScript.Interop.IJavaScriptBinaryCodec<global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid, ")
            .Append(mapping.CSharpType).AppendLine(">")
            .AppendLine("    {")
            .AppendLine("        public static uint EncodeArguments(")
            .AppendLine("            ref global::WebScene.JavaScript.Interop.JavaScriptBinaryWriter writer,")
            .AppendLine("            in global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid arguments)")
            .AppendLine("            => writer.BeginArray(0);")
            .AppendLine()
            .Append("        public static ").Append(mapping.CSharpType)
            .AppendLine(" DecodeResult(")
            .AppendLine("            global::WebScene.JavaScript.Interop.JavaScriptBinaryValue value,")
            .AppendLine("            global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker)")
            .AppendLine("        {");
        var result = EmitBinaryReadValue(
            source,
            generation,
            effectiveType,
            "value",
            "invoker",
            "            ");
        source.Append("            return ").Append(result).AppendLine(";")
            .AppendLine("        }")
            .AppendLine("    }");
    }

    private static void EmitGlobalFunction(
        StringBuilder source,
        GenerationContext generation,
        GlobalFunction function)
    {
        var method = function.Method;
        var typeParameters = method.TryGetProperty("typeParameters", out var genericParameters)
            ? genericParameters.EnumerateArray()
                .Select(static item => EscapeIdentifier(item.GetString()!))
                .ToArray()
            : [];
        var genericSuffix = typeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", typeParameters) + ">";
        var omitOptional = !function.Policy.TryGetProperty(
                               "omitOptionalParameters",
                               out var omitValue)
                           || omitValue.ValueKind != JsonValueKind.False;
        var parameters = method.GetProperty("parameters")
            .EnumerateArray()
            .Where(parameter =>
                !omitOptional
                || !parameter.GetProperty("optional").GetBoolean())
            .Select(parameter =>
            {
                var name = parameter.GetProperty("name").GetString()!;
                var optional = parameter.GetProperty("optional").GetBoolean();
                var rest = parameter.GetProperty("rest").GetBoolean();
                var mapping = MapOptionalParameterType(
                    generation,
                    parameter.GetProperty("type"),
                    optional,
                    $"{function.Name} parameter '{name}'");
                if (optional)
                {
                    mapping = mapping with
                    {
                        CSharpType =
                            $"global::WebScene.JavaScript.Interop.JavaScriptOptional<{mapping.CSharpType}>"
                    };
                }
                return new MappedParameter(
                    name,
                    mapping,
                    optional,
                    rest,
                    parameter.GetProperty("type").Clone());
            })
            .ToArray();
        var declaredReturn = method.GetProperty("returns");
        var promise = IsPromiseLikeReturn(declaredReturn);
        var effectiveReturn = Kind(declaredReturn) == "promise"
            ? declaredReturn.GetProperty("result")
            : declaredReturn;
        var returnsVoid = IsVoidLikeReturn(declaredReturn);
        var returnMapping = returnsVoid
            ? new TypeMapping("void", false)
            : MapType(
                generation,
                effectiveReturn,
                optional: false,
                $"{function.Name} return");
        var binarySupported = typeParameters.Length == 0
                              && parameters.All(parameter =>
                                  !parameter.Rest
                                  && CanEmitBinaryType(
                                      generation,
                                      parameter.Type))
                              && (returnsVoid
                                  || CanEmitBinaryType(
                                      generation,
                                      effectiveReturn));
        var binaryName = "__WebSceneBinary"
                         + PascalCase(function.Name)
                         + "Global";

        source.AppendLine()
            .Append("    public static ");
        if (!binarySupported)
        {
            source.Append("async ");
        }
        source.Append("global::System.Threading.Tasks.ValueTask");
        if (!returnsVoid)
        {
            source.Append('<').Append(returnMapping.CSharpType).Append('>');
        }
        source.Append(' ').Append(function.Name).Append(genericSuffix).AppendLine("(")
            .AppendLine("        global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker,");
        foreach (var parameter in parameters)
        {
            source.Append("        ").Append(parameter.Mapping.CSharpType)
                .Append(" @").Append(parameter.Name);
            if (parameter.Optional)
            {
                source.Append(" = default");
            }
            source.AppendLine(",");
        }
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {")
            .AppendLine("        global::System.ArgumentNullException.ThrowIfNull(invoker);");
        if (binarySupported)
        {
            EmitBinaryGlobalFunctionDispatch(
                source,
                parameters,
                returnsVoid,
                returnMapping,
                binaryName);
            source.AppendLine("    }");
            EmitBinaryInvocationCodec(
                source,
                generation,
                parameters,
                returnsVoid,
                effectiveReturn,
                returnMapping,
                binaryName,
                operation: "InvokeGlobal",
                globalName: function.GlobalName,
                memberName: null,
                promise: promise);
            return;
        }

        var arguments = ArgumentArray(parameters.Select(parameter =>
            new Parameter(
                parameter.Name,
                parameter.Mapping.IsBinding,
                parameter.Mapping.IsNullable,
                parameter.Optional,
                parameter.Rest)));
        if (promise)
        {
            if (returnsVoid)
            {
                source.Append("        await invoker.InvokeGlobalPromiseAsync<global::System.Text.Json.JsonElement>(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);");
            }
            else if (returnMapping.IsBinding && returnMapping.IsNullable)
            {
                source.Append("        var reference = await invoker.InvokeGlobalPromiseAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);")
                    .Append("        return reference is { } value ? new ")
                    .Append(returnMapping.NonNullableCSharpType)
                    .AppendLine("(invoker, value) : null;");
            }
            else if (returnMapping.IsBinding)
            {
                source.Append("        return new ").Append(returnMapping.CSharpType)
                    .Append("(invoker, await invoker.InvokeGlobalPromiseObjectAsync(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false));");
            }
            else if (returnMapping.IsFunctionReference && returnMapping.IsNullable)
            {
                source.Append("        var reference = await invoker.InvokeGlobalPromiseAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);")
                    .AppendLine("        return reference is { } value")
                    .AppendLine("            ? new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(invoker, value)")
                    .AppendLine("            : null;");
            }
            else if (returnMapping.IsFunctionReference)
            {
                source.Append("        return new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(invoker, await invoker.InvokeGlobalPromiseObjectAsync(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false));");
            }
            else if (returnMapping.IsObjectReference && !returnMapping.IsNullable)
            {
                source.Append("        return await invoker.InvokeGlobalPromiseObjectAsync(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);");
            }
            else if (returnMapping.RequiresWireConversion)
            {
                source.Append("        var wire = (await invoker.InvokeGlobalPromiseAsync<")
                    .Append(returnMapping.EffectiveWireCSharpType).Append(">(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false))!;")
                    .Append("        return ")
                    .Append(returnMapping.ConvertFromWire("wire", "invoker"))
                    .AppendLine(";");
            }
            else
            {
                source.Append("        return (await invoker.InvokeGlobalPromiseAsync<")
                    .Append(returnMapping.CSharpType).Append(">(")
                    .Append(Literal(function.GlobalName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false))!;");
            }
        }
        else if (returnsVoid)
        {
            source.Append("        await invoker.InvokeGlobalVoidAsync(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);");
        }
        else if (returnMapping.IsBinding && returnMapping.IsNullable)
        {
            source.Append("        var reference = await invoker.InvokeGlobalAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .Append("        return reference is { } value ? new ")
                .Append(returnMapping.NonNullableCSharpType)
                .AppendLine("(invoker, value) : null;");
        }
        else if (returnMapping.IsBinding)
        {
            source.Append("        return new ").Append(returnMapping.CSharpType)
                .Append("(invoker, await invoker.InvokeGlobalObjectAsync(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (returnMapping.IsFunctionReference && returnMapping.IsNullable)
        {
            source.Append("        var reference = await invoker.InvokeGlobalAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .AppendLine("        return reference is { } value")
                .AppendLine("            ? new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(invoker, value)")
                .AppendLine("            : null;");
        }
        else if (returnMapping.IsFunctionReference)
        {
            source.Append("        return new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(invoker, await invoker.InvokeGlobalObjectAsync(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (returnMapping.IsObjectReference && !returnMapping.IsNullable)
        {
            source.Append("        return await invoker.InvokeGlobalObjectAsync(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);");
        }
        else if (returnMapping.RequiresWireConversion)
        {
            source.Append("        var wire = (await invoker.InvokeGlobalAsync<")
                .Append(returnMapping.EffectiveWireCSharpType).Append(">(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;")
                .Append("        return ")
                .Append(returnMapping.ConvertFromWire("wire", "invoker"))
                .AppendLine(";");
        }
        else
        {
            source.Append("        return (await invoker.InvokeGlobalAsync<")
                .Append(returnMapping.CSharpType).Append(">(")
                .Append(Literal(function.GlobalName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;");
        }
        source.AppendLine("    }");
    }

    private static void EmitBinaryGlobalFunctionDispatch(
        StringBuilder source,
        IReadOnlyList<MappedParameter> parameters,
        bool returnsVoid,
        TypeMapping returnMapping,
        string binaryName)
    {
        var argumentsType = parameters.Count == 0
            ? "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid"
            : binaryName + "Arguments";
        var arguments = parameters.Count == 0
            ? "new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid()"
            : "new " + binaryName + "Arguments("
              + string.Join(
                  ", ",
                  parameters.Select(parameter => "@" + parameter.Name))
              + ")";
        source.AppendLine("        var binaryInvoker = invoker as global::WebScene.JavaScript.Interop.IJavaScriptBinaryInvoker")
            .AppendLine("            ?? throw new global::System.NotSupportedException(")
            .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
            .AppendLine("        if (!binaryInvoker.IsBinaryInteropAvailable)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.NotSupportedException(")
            .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
            .AppendLine("        }");
        if (returnsVoid)
        {
            source.Append("        return binaryInvoker.InvokeBinaryVoidAsync<")
                .Append(argumentsType).Append(", ").Append(binaryName)
                .Append("Codec>(").Append(binaryName)
                .Append("CallSite, default, ")
                .Append(arguments)
                .AppendLine(", cancellationToken);");
        }
        else
        {
            source.Append("        return binaryInvoker.InvokeBinaryAsync<")
                .Append(argumentsType).Append(", ")
                .Append(returnMapping.CSharpType).Append(", ")
                .Append(binaryName).Append("Codec>(")
                .Append(binaryName)
                .Append("CallSite, default, ")
                .Append(arguments)
                .AppendLine(", cancellationToken);");
        }
    }

    private static string GenerateAdapter(
        GenerationContext generation,
        Adapter adapter,
        string policyPath)
    {
        var adapterTypeParameters = adapter.Type.TryGetProperty(
            "typeParameters",
            out var declaredTypeParameters)
            ? declaredTypeParameters.EnumerateArray()
                .Select(static item => EscapeIdentifier(item.GetString()!))
                .ToArray()
            : [];
        var adapterTypeName = adapter.Name + (adapterTypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", adapterTypeParameters) + ">");
        var selectedMethods = adapter.Policy.TryGetProperty("methods", out var methods)
            ? methods.EnumerateArray()
                .Where(static method =>
                    !method.TryGetProperty("include", out var include)
                    || include.ValueKind != JsonValueKind.False)
                .Select(methodPolicy =>
                {
                    var sourceName = RequiredString(methodPolicy, "source", policyPath);
                    var overload = methodPolicy.TryGetProperty("overload", out var overloadValue)
                        ? overloadValue.GetInt32()
                        : 0;
                    var method = adapter.Type.GetProperty("methods")
                        .EnumerateArray()
                        .FirstOrDefault(candidate =>
                            string.Equals(
                                candidate.GetProperty("name").GetString(),
                                sourceName,
                                StringComparison.Ordinal)
                            && candidate.GetProperty("overload").GetInt32() == overload);
                    if (method.ValueKind == JsonValueKind.Undefined)
                    {
                        throw new InvalidDataException(
                            $"Adapter method '{adapter.Source}.{sourceName}' overload {overload} was not discovered.");
                    }
                    return new AdapterMethod(
                        sourceName,
                        OptionalString(methodPolicy, "name")
                            ?? SuggestedAdapterMethodName(sourceName, method),
                        method);
                })
                .ToArray()
            : adapter.Type.GetProperty("methods")
                .EnumerateArray()
                .Where(static method => method.GetProperty("overload").GetInt32() == 0)
                .Select(method => new AdapterMethod(
                    method.GetProperty("name").GetString()!,
                    SuggestedAdapterMethodName(
                        method.GetProperty("name").GetString()!,
                        method),
                    method))
                .ToArray();
        var binaryAdapterSupported = selectedMethods.All(
            method => CanEmitBinaryAdapterMethod(
                generation,
                adapter,
                method));
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        source.Append("namespace ").Append(generation.Namespace).AppendLine(";")
            .AppendLine()
            .Append("public abstract class ").Append(adapterTypeName)
            .AppendLine(binaryAdapterSupported
                ? " : global::WebScene.JavaScript.Interop.IJavaScriptBinaryCallbackTarget, global::WebScene.JavaScript.Interop.IJavaScriptObjectReferenceProvider, global::System.IAsyncDisposable"
                : " : global::WebScene.JavaScript.Interop.IJavaScriptCallbackTarget, global::WebScene.JavaScript.Interop.IJavaScriptObjectReferenceProvider, global::System.IAsyncDisposable")
            .AppendLine("{");
        source.Append("    private global::WebScene.JavaScript.Interop.")
            .Append(binaryAdapterSupported
                ? "IJavaScriptBinaryBidirectionalInvoker"
                : "IJavaScriptBidirectionalInvoker")
            .AppendLine("? __webSceneInvoker;")
            .AppendLine("    private global::WebScene.JavaScript.Interop.JavaScriptObjectReference __webSceneReference;")
            .AppendLine()
            .AppendLine("    public global::WebScene.JavaScript.Interop.JavaScriptObjectReference JavaScriptReference => __webSceneReference;")
            .AppendLine()
            .AppendLine("    public async global::System.Threading.Tasks.ValueTask<global::WebScene.JavaScript.Interop.JavaScriptObjectReference> RegisterAsync(");
        source.Append("        global::WebScene.JavaScript.Interop.")
            .Append(binaryAdapterSupported
                ? "IJavaScriptBinaryBidirectionalInvoker"
                : "IJavaScriptBidirectionalInvoker")
            .AppendLine(" invoker,")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {")
            .AppendLine("        global::System.ArgumentNullException.ThrowIfNull(invoker);")
            .AppendLine("        if (!__webSceneReference.IsEmpty)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.InvalidOperationException(\"This callback adapter is already registered.\");")
            .AppendLine("        }")
            .AppendLine("        __webSceneInvoker = invoker;");
        if (binaryAdapterSupported)
        {
            source.AppendLine("        __webSceneReference = await invoker.RegisterBinaryCallbackTargetAsync(")
                .AppendLine("            this,")
                .AppendLine("            new global::WebScene.JavaScript.Interop.JavaScriptBinaryCallbackMethod[]")
                .AppendLine("            {");
            for (var index = 0; index < selectedMethods.Length; index++)
            {
                var method = selectedMethods[index];
                source.Append("                new(")
                    .Append(Literal(method.SourceName)).Append(", ")
                    .Append(index).Append("U, global::WebScene.JavaScript.Interop.JavaScriptCallbackReturnKind.")
                    .Append(AdapterReturnKind(method.Method));
                if (AdapterReturnKind(method.Method) == "Synchronous"
                    && method.Method.GetProperty("parameters").GetArrayLength() == 0)
                {
                    source.Append(", true");
                }
                source.AppendLine("),");
            }
            source.AppendLine("            },")
                .AppendLine("            cancellationToken).ConfigureAwait(false);");
        }
        else
        {
            source.AppendLine("        __webSceneReference = await invoker.RegisterCallbackTargetAsync(")
                .AppendLine("            this,")
                .AppendLine("            new global::WebScene.JavaScript.Interop.JavaScriptCallbackMethod[]")
                .AppendLine("            {");
            foreach (var method in selectedMethods)
            {
                source.Append("                new(").Append(Literal(method.SourceName))
                    .Append(", global::WebScene.JavaScript.Interop.JavaScriptCallbackReturnKind.")
                    .Append(AdapterReturnKind(method.Method));
                if (AdapterReturnKind(method.Method) == "Synchronous"
                    && method.Method.GetProperty("parameters").GetArrayLength() == 0)
                {
                    source.Append(", global::WebScene.JavaScript.Interop.JavaScriptJson.Serialize(")
                        .Append(method.Name).Append("(cancellationToken))");
                }
                source.AppendLine("),");
            }
            source.AppendLine("            },")
                .AppendLine("            cancellationToken).ConfigureAwait(false);");
        }
        source
            .AppendLine("        return __webSceneReference;")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    public async global::System.Threading.Tasks.ValueTask DisposeAsync()")
            .AppendLine("    {")
            .AppendLine("        if (__webSceneInvoker is not null && !__webSceneReference.IsEmpty)")
            .AppendLine("        {")
            .AppendLine("            await __webSceneInvoker.ReleaseAsync(__webSceneReference).ConfigureAwait(false);")
            .AppendLine("            __webSceneReference = default;")
            .AppendLine("        }")
            .AppendLine("    }");

        foreach (var method in selectedMethods)
        {
            EmitAdapterMethod(source, generation, adapter, method);
        }
        if (binaryAdapterSupported)
        {
            EmitAdapterBinaryDispatch(
                source,
                generation,
                adapter,
                selectedMethods);
        }
        else
        {
            EmitAdapterDispatch(source, generation, adapter, selectedMethods);
        }
        return source.AppendLine("}").ToString();
    }

    private static void EmitAdapterMethod(
        StringBuilder source,
        GenerationContext generation,
        Adapter adapter,
        AdapterMethod method)
    {
        var erasedTypeParameters = AdapterMethodTypeParameters(method.Method);
        var declaredReturn = method.Method.GetProperty("returns");
        var promise = IsPromiseLikeReturn(declaredReturn);
        var effectiveReturn = Kind(declaredReturn) == "promise"
            ? declaredReturn.GetProperty("result")
            : declaredReturn;
        var returnsVoid = IsVoidLikeReturn(declaredReturn);
        var returnMapping = returnsVoid
            ? new TypeMapping("void", false)
            : MapAdapterType(
                generation,
                effectiveReturn,
                optional: false,
                $"{adapter.Name}.{method.Name} return",
                erasedTypeParameters);
        source.AppendLine();
        if (promise || returnsVoid)
        {
            source.Append("    public abstract global::System.Threading.Tasks.ValueTask");
            if (!returnsVoid)
            {
                source.Append('<').Append(returnMapping.CSharpType).Append('>');
            }
        }
        else
        {
            source.Append("    public abstract ").Append(returnMapping.CSharpType);
        }
        source.Append(' ').Append(method.Name).AppendLine("(");
        foreach (var parameter in method.Method.GetProperty("parameters").EnumerateArray())
        {
            var name = parameter.GetProperty("name").GetString()!;
            var optional = parameter.GetProperty("optional").GetBoolean();
            var mapping = MapAdapterParameterType(
                generation,
                parameter.GetProperty("type"),
                optional,
                $"{adapter.Name}.{method.Name} parameter '{name}'",
                erasedTypeParameters);
            var parameterType = optional
                ? $"global::WebScene.JavaScript.Interop.JavaScriptOptional<{mapping.CSharpType}>"
                : mapping.CSharpType;
            source.Append("        ").Append(parameterType)
                .Append(' ').Append(EscapeIdentifier(name)).AppendLine(",");
        }
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default);");
    }

    private static void EmitAdapterDispatch(
        StringBuilder source,
        GenerationContext generation,
        Adapter adapter,
        IReadOnlyList<AdapterMethod> methods)
    {
        source.AppendLine()
            .AppendLine("    async global::System.Threading.Tasks.ValueTask<object?> global::WebScene.JavaScript.Interop.IJavaScriptCallbackTarget.DispatchAsync(")
            .AppendLine("        string method,")
            .AppendLine("        global::System.Text.Json.JsonElement arguments,")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken)")
            .AppendLine("    {")
            .AppendLine("        var invoker = __webSceneInvoker ?? throw new global::System.InvalidOperationException(\"The callback adapter is not registered.\");")
            .AppendLine("        switch (method)")
            .AppendLine("        {");
        foreach (var method in methods)
        {
            var erasedTypeParameters = AdapterMethodTypeParameters(method.Method);
            var declaredReturn = method.Method.GetProperty("returns");
            var promise = IsPromiseLikeReturn(declaredReturn);
            var effectiveReturn = Kind(declaredReturn) == "promise"
                ? declaredReturn.GetProperty("result")
                : declaredReturn;
            var returnsVoid = IsVoidLikeReturn(declaredReturn);
            source.Append("            case ").Append(Literal(method.SourceName)).AppendLine(":")
                .Append("                ");
            if (promise && !returnsVoid)
            {
                source.Append("return await ");
            }
            else if (promise || returnsVoid)
            {
                source.Append("await ");
            }
            else
            {
                source.Append("return ");
            }
            source.Append(method.Name).AppendLine("(");
            var parameters = method.Method.GetProperty("parameters").EnumerateArray().ToArray();
            for (var index = 0; index < parameters.Length; index++)
            {
                var parameter = parameters[index];
                var optional = parameter.GetProperty("optional").GetBoolean();
                var mapping = MapAdapterParameterType(
                    generation,
                    parameter.GetProperty("type"),
                    optional,
                    $"{adapter.Name}.{method.Name} dispatch",
                    erasedTypeParameters);
                if (optional && mapping.IsBinding)
                {
                    source.Append("                    global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.HasValue(arguments, ")
                        .Append(index).AppendLine(")")
                        .Append("                        ? new global::WebScene.JavaScript.Interop.JavaScriptOptional<")
                        .Append(mapping.CSharpType).AppendLine(">(")
                        .Append("                            global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.IsNull(arguments, ")
                        .Append(index).AppendLine(")")
                        .AppendLine("                                ? null")
                        .Append("                                : new ")
                        .Append(mapping.NonNullableCSharpType)
                        .Append("(invoker, global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.Get<global::WebScene.JavaScript.Interop.JavaScriptObjectReference>(arguments, ")
                        .Append(index).AppendLine(", invoker)))")
                        .AppendLine("                        : default,");
                }
                else if (optional && mapping.IsCallbackWrapper)
                {
                    source.Append("                    global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.HasValue(arguments, ")
                        .Append(index).AppendLine(")")
                        .Append("                        ? new global::WebScene.JavaScript.Interop.JavaScriptOptional<")
                        .Append(mapping.CSharpType).AppendLine(">(")
                        .Append("                            global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.IsNull(arguments, ")
                        .Append(index).AppendLine(")")
                        .AppendLine("                                ? null")
                        .Append("                                : new ")
                        .Append(mapping.NonNullableCSharpType)
                        .Append("(invoker, global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.GetFunctionReference(arguments, ")
                        .Append(index).AppendLine(", invoker)))")
                        .AppendLine("                        : default,");
                }
                else if (optional)
                {
                    source.Append("                    global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.GetOptional<")
                        .Append(mapping.CSharpType).Append(">(arguments, ").Append(index)
                        .AppendLine(", invoker),");
                }
                else if (mapping.IsCallbackWrapper)
                {
                    source.Append("                    new ").Append(mapping.CSharpType)
                        .Append("(invoker, global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.GetFunctionReference(arguments, ")
                        .Append(index).AppendLine(", invoker)),");
                }
                else if (mapping.IsBinding)
                {
                    source.Append("                    new ")
                        .Append(mapping.NonNullableCSharpType)
                        .Append("(invoker, global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.Get<global::WebScene.JavaScript.Interop.JavaScriptObjectReference>(arguments, ")
                        .Append(index).AppendLine(", invoker)),");
                }
                else
                {
                    source.Append("                    global::WebScene.JavaScript.Interop.JavaScriptCallbackArguments.Get<")
                        .Append(mapping.CSharpType).Append(">(arguments, ").Append(index)
                        .AppendLine(", invoker)!,");
                }
            }
            source.AppendLine("                    cancellationToken)");
            if (promise || returnsVoid)
            {
                source.AppendLine("                    .ConfigureAwait(false);");
                if (returnsVoid)
                {
                    source.AppendLine("                return null;");
                }
            }
            else
            {
                source.AppendLine(";");
            }
        }
        source.AppendLine("            default:")
            .AppendLine("                throw new global::System.MissingMethodException($\"Unknown JavaScript callback method '{method}'.\");")
            .AppendLine("        }")
            .AppendLine("    }");
    }

    private static void EmitAdapterBinaryDispatch(
        StringBuilder source,
        GenerationContext generation,
        Adapter adapter,
        IReadOnlyList<AdapterMethod> methods)
    {
        var binaryActionHelpers = new StringBuilder();
        var binaryActionHelperIndex = 0;
        source.AppendLine()
            .AppendLine("    global::System.Threading.Tasks.ValueTask global::WebScene.JavaScript.Interop.IJavaScriptBinaryCallbackTarget.DispatchBinaryAsync(")
            .AppendLine("        uint methodId,")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryValue arguments,")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryCallbackCompletion completion,")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken)")
            .AppendLine("    {")
            .AppendLine("        var invoker = __webSceneInvoker ?? throw new global::System.InvalidOperationException(\"The callback adapter is not registered.\");")
            .AppendLine("        if (arguments.Kind != global::WebScene.JavaScript.Interop.JavaScriptBinaryValueKind.Array)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.IO.InvalidDataException(\"Binary callback arguments must be an array.\");")
            .AppendLine("        }")
            .AppendLine("        switch (methodId)")
            .AppendLine("        {");
        for (var methodIndex = 0; methodIndex < methods.Count; methodIndex++)
        {
            source.Append("            case ").Append(methodIndex)
                .Append("U: return __WebSceneDispatchBinaryCallback")
                .Append(methodIndex)
                .AppendLine("(arguments, completion, invoker, cancellationToken);");
        }
        source.AppendLine("            default:")
            .AppendLine("                throw new global::System.MissingMethodException($\"Unknown binary JavaScript callback method ID {methodId}.\");")
            .AppendLine("        }")
            .AppendLine("    }");

        for (var methodIndex = 0; methodIndex < methods.Count; methodIndex++)
        {
            var method = methods[methodIndex];
            var erasedTypeParameters = AdapterMethodTypeParameters(method.Method);
            var declaredReturn = method.Method.GetProperty("returns");
            var promise = IsPromiseLikeReturn(declaredReturn);
            var effectiveReturn = Kind(declaredReturn) == "promise"
                ? declaredReturn.GetProperty("result")
                : declaredReturn;
            var returnsVoid = IsVoidLikeReturn(declaredReturn);
            source.AppendLine()
                .Append("    private global::System.Threading.Tasks.ValueTask __WebSceneDispatchBinaryCallback")
                .Append(methodIndex).AppendLine("(")
                .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryValue arguments,")
                .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryCallbackCompletion completion,")
                .AppendLine("        global::WebScene.JavaScript.Interop.IJavaScriptBidirectionalInvoker invoker,")
                .AppendLine("        global::System.Threading.CancellationToken cancellationToken)")
                .AppendLine("    {");
            var decodedArguments = new List<string>();
            var parameters = method.Method.GetProperty("parameters")
                .EnumerateArray()
                .ToArray();
            for (var parameterIndex = 0;
                 parameterIndex < parameters.Length;
                 parameterIndex++)
            {
                decodedArguments.Add(EmitAdapterBinaryArgument(
                    source,
                    binaryActionHelpers,
                    ref binaryActionHelperIndex,
                    generation,
                    adapter,
                    method,
                    parameters[parameterIndex],
                    parameterIndex,
                    erasedTypeParameters,
                    "        "));
            }
            decodedArguments.Add("cancellationToken");
            var invocation = method.Name + "("
                + string.Join(", ", decodedArguments) + ")";
            if (returnsVoid)
            {
                var pending = generation.NextLocal("callbackPending");
                source.Append("        var ").Append(pending)
                    .Append(" = ").Append(invocation).AppendLine(";")
                    .Append("        if (").Append(pending)
                    .AppendLine(".IsCompletedSuccessfully)")
                    .AppendLine("        {")
                    .Append("            ").Append(pending)
                    .AppendLine(".GetAwaiter().GetResult();")
                    .AppendLine("            completion.SetVoid();")
                    .AppendLine("            return global::System.Threading.Tasks.ValueTask.CompletedTask;")
                    .AppendLine("        }")
                    .Append("        return __WebSceneAwaitBinaryCallback")
                    .Append(methodIndex).Append('(').Append(pending)
                    .AppendLine(", completion);");
            }
            else if (promise)
            {
                if (!CanEmitBinaryType(generation, effectiveReturn))
                {
                    source.AppendLine("        throw new global::System.NotSupportedException(\"This callback return type has no generated binary codec.\");");
                }
                else
                {
                    var returnMapping = MapAdapterType(
                        generation,
                        effectiveReturn,
                        optional: false,
                        $"{adapter.Name}.{method.Name} binary return",
                        erasedTypeParameters);
                    var pending = generation.NextLocal("callbackPending");
                    var result = generation.NextLocal("callbackResult");
                    source.Append("        var ").Append(pending)
                        .Append(" = ").Append(invocation).AppendLine(";")
                        .Append("        if (").Append(pending)
                        .AppendLine(".IsCompletedSuccessfully)")
                        .AppendLine("        {")
                        .Append("            var ").Append(result)
                        .Append(" = ").Append(pending)
                        .AppendLine(".GetAwaiter().GetResult();")
                        .Append("            completion.SetResult<")
                        .Append(returnMapping.CSharpType).Append(", __WebSceneCallbackResultCodec")
                        .Append(methodIndex).Append(">(in ").Append(result)
                        .AppendLine(");")
                        .AppendLine("            return global::System.Threading.Tasks.ValueTask.CompletedTask;")
                        .AppendLine("        }")
                        .Append("        return __WebSceneAwaitBinaryCallback")
                        .Append(methodIndex).Append('(').Append(pending)
                        .AppendLine(", completion);");
                }
            }
            else
            {
                if (!CanEmitBinaryType(generation, effectiveReturn))
                {
                    source.AppendLine("        throw new global::System.NotSupportedException(\"This synchronous callback return type has no generated binary codec.\");");
                }
                else
                {
                    var returnMapping = MapAdapterType(
                        generation,
                        effectiveReturn,
                        optional: false,
                        $"{adapter.Name}.{method.Name} binary return",
                        erasedTypeParameters);
                    var result = generation.NextLocal("callbackResult");
                    source.Append("        var ").Append(result)
                        .Append(" = ").Append(invocation).AppendLine(";")
                        .Append("        completion.SetResult<")
                        .Append(returnMapping.CSharpType)
                        .Append(", __WebSceneCallbackResultCodec")
                        .Append(methodIndex).Append(">(in ").Append(result)
                        .AppendLine(");")
                        .AppendLine("        return global::System.Threading.Tasks.ValueTask.CompletedTask;");
                }
            }
            source.AppendLine("    }");
        }

        for (var methodIndex = 0; methodIndex < methods.Count; methodIndex++)
        {
            var method = methods[methodIndex];
            var declaredReturn = method.Method.GetProperty("returns");
            var promise = IsPromiseLikeReturn(declaredReturn);
            var effectiveReturn = Kind(declaredReturn) == "promise"
                ? declaredReturn.GetProperty("result")
                : declaredReturn;
            var returnsVoid = IsVoidLikeReturn(declaredReturn);
            var erasedTypeParameters = AdapterMethodTypeParameters(method.Method);
            if (returnsVoid)
            {
                source.AppendLine()
                    .Append("    private static async global::System.Threading.Tasks.ValueTask __WebSceneAwaitBinaryCallback")
                    .Append(methodIndex).AppendLine("(")
                    .AppendLine("        global::System.Threading.Tasks.ValueTask pending,")
                    .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryCallbackCompletion completion)")
                    .AppendLine("    {")
                    .AppendLine("        await pending.ConfigureAwait(false);")
                    .AppendLine("        completion.SetVoid();")
                    .AppendLine("    }");
                continue;
            }
            if (!CanEmitBinaryType(generation, effectiveReturn))
            {
                continue;
            }
            var returnMapping = MapAdapterType(
                generation,
                effectiveReturn,
                optional: false,
                $"{adapter.Name}.{method.Name} binary result codec",
                erasedTypeParameters);
            if (promise)
            {
                source.AppendLine()
                    .Append("    private static async global::System.Threading.Tasks.ValueTask __WebSceneAwaitBinaryCallback")
                    .Append(methodIndex).AppendLine("(")
                    .Append("        global::System.Threading.Tasks.ValueTask<")
                    .Append(returnMapping.CSharpType).AppendLine("> pending,")
                    .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryCallbackCompletion completion)")
                    .AppendLine("    {")
                    .AppendLine("        var result = await pending.ConfigureAwait(false);")
                    .Append("        completion.SetResult<")
                    .Append(returnMapping.CSharpType)
                    .Append(", __WebSceneCallbackResultCodec")
                    .Append(methodIndex).AppendLine(">(in result);")
                    .AppendLine("    }");
            }
            source.AppendLine()
                .Append("    private readonly struct __WebSceneCallbackResultCodec")
                .Append(methodIndex)
                .Append(" : global::WebScene.JavaScript.Interop.IJavaScriptBinaryCallbackResultCodec<")
                .Append(returnMapping.CSharpType).AppendLine(">")
                .AppendLine("    {")
                .AppendLine("        public static uint EncodeResult(")
                .AppendLine("            ref global::WebScene.JavaScript.Interop.JavaScriptBinaryWriter writer,")
                .Append("            in ").Append(returnMapping.CSharpType)
                .AppendLine(" result)")
                .AppendLine("        {");
            var encoded = EmitBinaryWriteValue(
                source,
                generation,
                effectiveReturn,
                "result",
                "            ");
            source.Append("            return ").Append(encoded)
                .AppendLine(";")
                .AppendLine("        }")
                .AppendLine("    }");
        }

        source.Append(binaryActionHelpers)
            .AppendLine()
            .AppendLine("    uint global::WebScene.JavaScript.Interop.IJavaScriptBinaryCallbackTarget.EncodeSynchronousResult(")
            .AppendLine("        uint methodId,")
            .AppendLine("        ref global::WebScene.JavaScript.Interop.JavaScriptBinaryWriter writer,")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken)")
            .AppendLine("    {")
            .AppendLine("        switch (methodId)")
            .AppendLine("        {");
        for (var methodIndex = 0; methodIndex < methods.Count; methodIndex++)
        {
            var method = methods[methodIndex];
            var declaredReturn = method.Method.GetProperty("returns");
            var effectiveReturn = Kind(declaredReturn) == "promise"
                ? declaredReturn.GetProperty("result")
                : declaredReturn;
            if (AdapterReturnKind(method.Method) != "Synchronous"
                || method.Method.GetProperty("parameters").GetArrayLength() != 0
                || !CanEmitBinaryType(generation, effectiveReturn))
            {
                continue;
            }
            var result = generation.NextLocal("synchronousResult");
            source.Append("            case ").Append(methodIndex)
                .AppendLine("U:")
                .AppendLine("            {")
                .Append("                var ").Append(result)
                .Append(" = ").Append(method.Name)
                .AppendLine("(cancellationToken);")
                .Append("                return __WebSceneCallbackResultCodec")
                .Append(methodIndex).Append(".EncodeResult(ref writer, in ")
                .Append(result).AppendLine(");")
                .AppendLine("            }");
        }
        source.AppendLine("            default:")
            .AppendLine("                throw new global::System.NotSupportedException($\"Callback method {methodId} has no precomputed synchronous result.\");")
            .AppendLine("        }")
            .AppendLine("    }");
    }

    private static string EmitAdapterBinaryArgument(
        StringBuilder source,
        StringBuilder binaryActionHelpers,
        ref int binaryActionHelperIndex,
        GenerationContext generation,
        Adapter adapter,
        AdapterMethod method,
        JsonElement parameter,
        int parameterIndex,
        ISet<string> erasedTypeParameters,
        string indent)
    {
        var type = parameter.GetProperty("type");
        var optional = parameter.GetProperty("optional").GetBoolean();
        var valueType = OptionalParameterValueType(type, optional);
        var mapping = MapAdapterParameterType(
            generation,
            type,
            optional,
            $"{adapter.Name}.{method.Name} binary dispatch",
            erasedTypeParameters);
        if (!optional)
        {
            var value = generation.NextLocal("callbackArgument");
            source.Append(indent).Append("var ").Append(value)
                .Append(" = arguments.GetArrayItem(")
                .Append(parameterIndex).AppendLine(");");
            return EmitAdapterBinaryDecodedValue(
                source,
                binaryActionHelpers,
                ref binaryActionHelperIndex,
                generation,
                valueType,
                mapping,
                value,
                "invoker",
                indent);
        }

        var optionalValue = generation.NextLocal("callbackOptional");
        var valueLocal = generation.NextLocal("callbackArgument");
        source.Append(indent)
            .Append("global::WebScene.JavaScript.Interop.JavaScriptOptional<")
            .Append(mapping.CSharpType).Append("> ").Append(optionalValue)
            .AppendLine(" = default;")
            .Append(indent).Append("if (").Append(parameterIndex)
            .AppendLine(" < arguments.Count)")
            .Append(indent).AppendLine("{")
            .Append(indent).Append("    var ").Append(valueLocal)
            .Append(" = arguments.GetArrayItem(").Append(parameterIndex)
            .AppendLine(");")
            .Append(indent).Append("    if (").Append(valueLocal)
            .AppendLine(".Kind != global::WebScene.JavaScript.Interop.JavaScriptBinaryValueKind.Undefined)")
            .Append(indent).AppendLine("    {");
        if (mapping.IsBinding || mapping.IsCallbackWrapper
            || IsCallbackType(type))
        {
            source.Append(indent).Append("        if (").Append(valueLocal)
                .AppendLine(".Kind == global::WebScene.JavaScript.Interop.JavaScriptBinaryValueKind.Null)")
                .Append(indent).AppendLine("        {")
                .Append(indent).Append("            ").Append(optionalValue)
                .Append(" = new global::WebScene.JavaScript.Interop.JavaScriptOptional<")
                .Append(mapping.CSharpType).AppendLine(">(default);")
                .Append(indent).AppendLine("        }")
                .Append(indent).AppendLine("        else")
                .Append(indent).AppendLine("        {");
            var decoded = EmitAdapterBinaryDecodedValue(
                source,
                binaryActionHelpers,
                ref binaryActionHelperIndex,
                generation,
                valueType,
                mapping,
                valueLocal,
                "invoker",
                indent + "            ");
            source.Append(indent).Append("            ").Append(optionalValue)
                .Append(" = new global::WebScene.JavaScript.Interop.JavaScriptOptional<")
                .Append(mapping.CSharpType).Append(">(").Append(decoded)
                .AppendLine(");")
                .Append(indent).AppendLine("        }");
        }
        else
        {
            var decoded = EmitAdapterBinaryDecodedValue(
                source,
                binaryActionHelpers,
                ref binaryActionHelperIndex,
                generation,
                valueType,
                mapping,
                valueLocal,
                "invoker",
                indent + "        ");
            source.Append(indent).Append("        ").Append(optionalValue)
                .Append(" = new global::WebScene.JavaScript.Interop.JavaScriptOptional<")
                .Append(mapping.CSharpType).Append(">(").Append(decoded)
                .AppendLine(");");
        }
        source.Append(indent).AppendLine("    }")
            .Append(indent).AppendLine("}");
        return optionalValue;
    }

    private static string EmitAdapterBinaryDecodedValue(
        StringBuilder source,
        StringBuilder binaryActionHelpers,
        ref int binaryActionHelperIndex,
        GenerationContext generation,
        JsonElement type,
        TypeMapping mapping,
        string valueExpression,
        string invokerExpression,
        string indent)
    {
        if (IsCallbackType(type))
        {
            var function = generation.NextLocal("callbackFunction");
            source.Append(indent).Append("var ").Append(function)
                .Append(" = new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(")
                .Append(invokerExpression).Append(", ")
                .Append(valueExpression).AppendLine(".GetHandle());");
            if (!mapping.IsCallbackWrapper)
            {
                return function;
            }
            var wrapper = generation.NextLocal("callbackWrapper");
            var binaryActionHelper = "__WebSceneInvokeBinaryAction"
                + binaryActionHelperIndex++;
            EmitBinaryCallbackWrapperHelper(
                binaryActionHelpers,
                generation,
                type,
                binaryActionHelper);
            source.Append(indent).Append("var ").Append(wrapper)
                .Append(" = new ").Append(mapping.NonNullableCSharpType)
                .Append('(').Append(invokerExpression).Append(", ")
                .Append(function).Append(", ")
                .Append(binaryActionHelper).AppendLine(");");
            return wrapper;
        }
        if (mapping.IsBinding)
        {
            var binding = generation.NextLocal("callbackBinding");
            source.Append(indent).Append("var ").Append(binding)
                .Append(" = new ").Append(mapping.NonNullableCSharpType)
                .Append('(').Append(invokerExpression).Append(", ")
                .Append(valueExpression).AppendLine(".GetHandle());");
            return binding;
        }
        if (!CanEmitBinaryType(generation, type))
        {
            source.Append(indent)
                .AppendLine("throw new global::System.NotSupportedException(\"This callback argument type has no generated binary codec.\");");
            return "default!";
        }
        return EmitBinaryReadValue(
            source,
            generation,
            type,
            valueExpression,
            invokerExpression,
            indent);
    }

    private static void EmitBinaryCallbackWrapperHelper(
        StringBuilder source,
        GenerationContext generation,
        JsonElement type,
        string helperName)
    {
        var callback = Kind(type) == "callback"
            ? type
            : FlattenUnionTypes(type).First(
                static candidate => Kind(candidate) == "callback");
        var signature = callback.GetProperty("signatures")[0];
        var parameters = signature.GetProperty("parameters")
            .EnumerateArray()
            .ToArray();
        var mappings = parameters
            .Select(parameter => MapType(
                generation,
                parameter.GetProperty("type"),
                optional: parameter.TryGetProperty(
                              "optional",
                              out var optional)
                          && optional.GetBoolean(),
                helperName))
            .ToArray();
        var argumentsType = parameters.Length switch
        {
            0 => "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid",
            1 => mappings[0].CSharpType,
            _ => TupleType(
                mappings.Select(static mapping => mapping.CSharpType)
                    .ToArray())
        };
        var codecName = helperName + "Codec";

        source.AppendLine()
            .Append("    private static global::System.Threading.Tasks.ValueTask ")
            .Append(helperName).AppendLine("(")
            .AppendLine("        global::WebScene.JavaScript.Interop.IJavaScriptBinaryBidirectionalInvoker invoker,")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptObjectReference function,");
        for (var index = 0; index < parameters.Length; index++)
        {
            source.Append("        ").Append(mappings[index].CSharpType)
                .Append(" argument").Append(index + 1).AppendLine(",");
        }
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)")
            .AppendLine("    {")
            .Append("        return invoker.InvokeBinaryFunctionVoidAsync<")
            .Append(argumentsType).Append(", ").Append(codecName)
            .AppendLine(">(")
            .AppendLine("            function,");
        if (parameters.Length == 0)
        {
            source.AppendLine("            new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid(),");
        }
        else if (parameters.Length == 1)
        {
            source.AppendLine("            argument1,");
        }
        else
        {
            source.Append("            (")
                .Append(string.Join(
                    ", ",
                    Enumerable.Range(1, parameters.Length)
                        .Select(static index => "argument" + index)))
                .AppendLine("),");
        }
        source.AppendLine("            cancellationToken);")
            .AppendLine("    }")
            .AppendLine()
            .Append("    private readonly struct ").Append(codecName)
            .Append(" : global::WebScene.JavaScript.Interop.IJavaScriptBinaryCodec<")
            .Append(argumentsType)
            .AppendLine(", global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid>")
            .AppendLine("    {")
            .AppendLine("        public static uint EncodeArguments(")
            .AppendLine("            ref global::WebScene.JavaScript.Interop.JavaScriptBinaryWriter writer,")
            .Append("            in ").Append(argumentsType)
            .AppendLine(" arguments)")
            .AppendLine("        {")
            .Append("            var root = writer.BeginArray(")
            .Append(parameters.Length).AppendLine(");");
        for (var index = 0; index < parameters.Length; index++)
        {
            var expression = parameters.Length == 1
                ? "arguments"
                : "arguments.Item" + (index + 1);
            var optional = parameters[index].TryGetProperty(
                               "optional",
                               out var optionalValue)
                           && optionalValue.GetBoolean();
            var encoded = EmitBinaryWriteCallbackArgument(
                source,
                generation,
                parameters[index].GetProperty("type"),
                expression,
                optional,
                "            ");
            source.Append("            writer.SetArrayItem(root, ")
                .Append(index).Append(", ").Append(encoded)
                .AppendLine(");");
        }
        source.AppendLine("            return root;")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        public static global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid DecodeResult(")
            .AppendLine("            global::WebScene.JavaScript.Interop.JavaScriptBinaryValue value,")
            .AppendLine("            global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker)")
            .AppendLine("            => new();")
            .AppendLine("    }");
    }

    private static string EmitBinaryWriteCallbackArgument(
        StringBuilder source,
        GenerationContext generation,
        JsonElement type,
        string valueExpression,
        bool optional,
        string indent)
    {
        if (!optional)
        {
            return EmitBinaryWriteValue(
                source,
                generation,
                type,
                valueExpression,
                indent);
        }

        var result = generation.NextLocal("binaryCallbackValue");
        source.Append(indent).Append("uint ").Append(result)
            .AppendLine(";")
            .Append(indent).Append("if (").Append(valueExpression)
            .AppendLine(" is null)")
            .Append(indent).AppendLine("{")
            .Append(indent).Append("    ").Append(result)
            .AppendLine(" = writer.WriteNull();")
            .Append(indent).AppendLine("}")
            .Append(indent).AppendLine("else")
            .Append(indent).AppendLine("{");
        var payloadType = Kind(type) == "union"
                          && TryGetBinaryUnionPayloadType(
                              type,
                              out var unionPayload)
            ? unionPayload
            : type;
        var requiredMapping = MapType(
            generation,
            payloadType,
            optional: false,
            "binary callback argument");
        var concreteExpression = IsValueType(requiredMapping.CSharpType)
            ? valueExpression + ".Value"
            : valueExpression;
        var encoded = EmitBinaryWriteValue(
            source,
            generation,
            payloadType,
            concreteExpression,
            indent + "    ");
        source.Append(indent).Append("    ").Append(result)
            .Append(" = ").Append(encoded).AppendLine(";")
            .Append(indent).AppendLine("}");
        return result;
    }

    private static bool IsCallbackType(JsonElement type)
    {
        if (Kind(type) == "callback") return true;
        return Kind(type) == "union"
               && FlattenUnionTypes(type).Any(
                   static candidate => Kind(candidate) == "callback");
    }

    private static bool CanEmitBinaryAdapterMethod(
        GenerationContext generation,
        Adapter adapter,
        AdapterMethod method)
    {
        static bool ContainsErasedTypeParameter(
            JsonElement type,
            ISet<string> erased)
            => erased.Count != 0
               && ContainsTypeParameter(type, erased);

        var erased = AdapterMethodTypeParameters(method.Method);
        foreach (var parameter in method.Method.GetProperty("parameters")
                     .EnumerateArray())
        {
            var type = parameter.GetProperty("type");
            if (ContainsErasedTypeParameter(type, erased)
                || !IsCallbackType(type)
                && !CanEmitBinaryType(generation, type))
            {
                return false;
            }
        }
        var declaredReturn = method.Method.GetProperty("returns");
        if (IsVoidLikeReturn(declaredReturn))
        {
            return true;
        }
        var effectiveReturn = Kind(declaredReturn) == "promise"
            ? declaredReturn.GetProperty("result")
            : declaredReturn;
        return !ContainsErasedTypeParameter(effectiveReturn, erased)
               && CanEmitBinaryType(generation, effectiveReturn);
    }

    private static TypeMapping MapAdapterType(
        GenerationContext generation,
        JsonElement type,
        bool optional,
        string member,
        ISet<string>? erasedTypeParameters = null)
    {
        if (erasedTypeParameters is { Count: > 0 }
            && ContainsTypeParameter(type, erasedTypeParameters))
        {
            var callback = Kind(type) == "callback"
                || Kind(type) == "union"
                && type.GetProperty("types").EnumerateArray().Any(
                    static candidate => Kind(candidate) == "callback");
            var erased = callback
                ? "global::WebScene.JavaScript.Interop.JavaScriptFunctionReference"
                : "global::System.Text.Json.JsonElement";
            return new TypeMapping(optional ? Nullable(erased) : erased, false);
        }
        if (Kind(type) == "callback")
        {
            var wrapper = ResolveCallbackWrapper(generation, type, member);
            return new TypeMapping(
                optional ? Nullable(wrapper) : wrapper,
                false,
                IsCallbackWrapper: wrapper
                    != "global::WebScene.JavaScript.Interop.JavaScriptFunctionReference");
        }
        if (Kind(type) == "union")
        {
            var nonNull = type.GetProperty("types").EnumerateArray()
                .Where(static candidate => Kind(candidate) is not ("null" or "undefined"))
                .ToArray();
            if (nonNull.Length == 1 && Kind(nonNull[0]) == "callback")
            {
                var wrapper = ResolveCallbackWrapper(
                    generation,
                    nonNull[0],
                    member);
                var nullable = type.GetProperty("types").EnumerateArray().Any(
                    static candidate => Kind(candidate) is "null" or "undefined");
                return new TypeMapping(
                    optional || nullable ? Nullable(wrapper) : wrapper,
                    false,
                    IsCallbackWrapper: wrapper
                        != "global::WebScene.JavaScript.Interop.JavaScriptFunctionReference");
            }
        }
        return MapType(generation, type, optional, member);
    }

    private static TypeMapping MapAdapterParameterType(
        GenerationContext generation,
        JsonElement type,
        bool optional,
        string member,
        ISet<string>? erasedTypeParameters)
    {
        if (!optional)
        {
            return MapAdapterType(
                generation,
                type,
                optional: false,
                member,
                erasedTypeParameters);
        }

        var callback = Kind(type) == "callback";
        if (Kind(type) == "union")
        {
            var concrete = type.GetProperty("types").EnumerateArray()
                .Where(static candidate => Kind(candidate) is not ("null" or "undefined"))
                .ToArray();
            callback = concrete.Length == 1 && Kind(concrete[0]) == "callback";
        }
        if (callback
            || erasedTypeParameters is { Count: > 0 }
            && ContainsTypeParameter(type, erasedTypeParameters))
        {
            return MapAdapterType(
                generation,
                type,
                optional: false,
                member,
                erasedTypeParameters);
        }
        return MapOptionalParameterType(generation, type, optional: true, member);
    }

    private static HashSet<string> AdapterMethodTypeParameters(JsonElement method)
        => method.TryGetProperty("typeParameters", out var parameters)
            ? new HashSet<string>(
                parameters.EnumerateArray()
                    .Select(static parameter => parameter.GetString()!),
                StringComparer.Ordinal)
            : new HashSet<string>(StringComparer.Ordinal);

    private static bool ContainsTypeParameter(
        JsonElement value,
        ISet<string> names)
    {
        if (value.ValueKind == JsonValueKind.Object)
        {
            if (value.TryGetProperty("kind", out var kind)
                && kind.GetString() == "typeParameter"
                && value.TryGetProperty("name", out var name)
                && names.Contains(name.GetString()!))
            {
                return true;
            }
            return value.EnumerateObject().Any(
                property => ContainsTypeParameter(property.Value, names));
        }
        return value.ValueKind == JsonValueKind.Array
               && value.EnumerateArray().Any(item => ContainsTypeParameter(item, names));
    }

    private static string ResolveCallbackWrapper(
        GenerationContext generation,
        JsonElement callback,
        string member)
    {
        var signatures = callback.GetProperty("signatures");
        if (signatures.GetArrayLength() != 1)
        {
            return "global::WebScene.JavaScript.Interop.JavaScriptFunctionReference";
        }
        var signature = signatures[0];
        if (Kind(signature.GetProperty("returns")) != "void")
        {
            return "global::WebScene.JavaScript.Interop.JavaScriptFunctionReference";
        }
        var parameters = signature.GetProperty("parameters")
            .EnumerateArray()
            .Select(parameter => MapType(
                generation,
                parameter.GetProperty("type"),
                optional: parameter.TryGetProperty("optional", out var optional)
                          && optional.GetBoolean(),
                member).CSharpType)
            .ToArray();
        if (parameters.Length == 0)
        {
            return "global::WebScene.JavaScript.Interop.JavaScriptAction";
        }
        if (parameters.Length <= 4)
        {
            return "global::WebScene.JavaScript.Interop.JavaScriptAction<"
                   + string.Join(", ", parameters)
                   + ">";
        }
        return "global::WebScene.JavaScript.Interop.JavaScriptTupleAction<"
               + TupleType(parameters)
               + ">";
    }

    private static string AdapterReturnKind(JsonElement method)
    {
        var returns = method.GetProperty("returns");
        if (IsPromiseLikeReturn(returns))
        {
            return "Promise";
        }
        return IsVoidLikeReturn(returns) ? "Void" : "Synchronous";
    }

    private static string SuggestedAdapterMethodName(
        string sourceName,
        JsonElement method)
        => PascalCase(sourceName)
           + (AdapterReturnKind(method) == "Synchronous" ? string.Empty : "Async");

}
