using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace WebScene.JavaScript.Interop.Generator;

public sealed partial class ManifestJavaScriptBindingGenerator
{
    private static string GenerateModel(
        GenerationContext generation,
        Model model)
    {
        var kind = Kind(model.Type);
        if (kind == "enum")
        {
            return GenerateEnumModel(generation.Namespace, model);
        }
        if (kind == "typeAlias"
            && model.Type.TryGetProperty("aliasTarget", out var aliasTarget))
        {
            if (IsStringLiteralUnion(aliasTarget))
            {
                return GenerateStringUnionModel(generation.Namespace, model, aliasTarget);
            }
            return GenerateAliasModel(generation, model, aliasTarget);
        }

        var objectType = model.Type;
        var typeParameters = model.Type.TryGetProperty("typeParameters", out var parameters)
            ? parameters.EnumerateArray().Select(static item => item.GetString()!).ToArray()
            : [];
        var genericSuffix = typeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", typeParameters.Select(EscapeIdentifier)) + ">";
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        source.Append("namespace ").Append(generation.Namespace).AppendLine(";")
            .AppendLine();
        EmitObjectModel(
            source,
            generation,
            model.Name + genericSuffix,
            model.Name,
            objectType,
            typeParameters);
        return source.ToString();
    }

    private static string GenerateAliasModel(
        GenerationContext generation,
        Model model,
        JsonElement aliasTarget)
    {
        var typeParameters = model.Type.TryGetProperty("typeParameters", out var parameters)
            ? parameters.EnumerateArray().Select(static item => item.GetString()!).ToArray()
            : [];
        var escapedTypeParameters = typeParameters.Select(EscapeIdentifier).ToArray();
        var genericSuffix = escapedTypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", escapedTypeParameters) + ">";
        var modelType = model.Name + genericSuffix;
        if (Kind(aliasTarget) == "inlineObject")
        {
            var source = new StringBuilder(
                """
                // <auto-generated />
                #nullable enable

                """);
            source.Append("namespace ").Append(generation.Namespace).AppendLine(";")
                .AppendLine();
            EmitObjectModel(
                source,
                generation,
                modelType,
                model.Name,
                aliasTarget,
                typeParameters);
            return source.ToString();
        }
        var underlying = MapType(
            generation,
            aliasTarget,
            optional: false,
            $"alias '{model.Source}'").CSharpType;
        var sourceBuilder = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        sourceBuilder.Append("namespace ").Append(generation.Namespace).AppendLine(";")
            .AppendLine()
            .Append("[global::System.Text.Json.Serialization.JsonConverter(typeof(")
            .Append(model.Name).Append(escapedTypeParameters.Length == 0
                ? "JsonConverter"
                : "JsonConverterFactory").AppendLine("))]")
            .Append("public readonly record struct ").Append(modelType)
            .Append('(').Append(underlying).AppendLine(" Value)")
            .AppendLine("{")
            .Append("    public static implicit operator ").Append(underlying)
            .Append('(').Append(modelType).AppendLine(" value) => value.Value;")
            .Append("    public static implicit operator ").Append(modelType)
            .Append('(').Append(underlying).AppendLine(" value) => new(value);")
            .AppendLine("    public override string? ToString() => global::System.Convert.ToString(Value, global::System.Globalization.CultureInfo.InvariantCulture);")
            .AppendLine("}");
        if (escapedTypeParameters.Length > 0)
        {
            var openModel = OpenGenericType(model.Name, escapedTypeParameters.Length);
            var openConverter = OpenGenericType(
                model.Name + "JsonConverter",
                escapedTypeParameters.Length);
            sourceBuilder.AppendLine()
                .Append("public sealed class ").Append(model.Name)
                .AppendLine("JsonConverterFactory : global::System.Text.Json.Serialization.JsonConverterFactory")
                .AppendLine("{")
                .AppendLine("    public override bool CanConvert(global::System.Type typeToConvert)")
                .Append("        => typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof(")
                .Append(openModel).AppendLine(");")
                .AppendLine()
                .AppendLine("    public override global::System.Text.Json.Serialization.JsonConverter CreateConverter(")
                .AppendLine("        global::System.Type typeToConvert,")
                .AppendLine("        global::System.Text.Json.JsonSerializerOptions options)")
                .Append("        => (global::System.Text.Json.Serialization.JsonConverter)global::System.Activator.CreateInstance(typeof(")
                .Append(openConverter)
                .AppendLine(").MakeGenericType(typeToConvert.GetGenericArguments()))!;")
                .AppendLine("}");
        }
        sourceBuilder.AppendLine()
            .Append("public sealed class ").Append(model.Name)
            .Append("JsonConverter").Append(genericSuffix)
            .Append(" : global::System.Text.Json.Serialization.JsonConverter<")
            .Append(modelType).AppendLine(">")
            .AppendLine("{")
            .Append("    public override ").Append(modelType)
            .AppendLine(" Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)")
            .Append("        => new(global::System.Text.Json.JsonSerializer.Deserialize<")
            .Append(underlying).AppendLine(">(ref reader, options)!);")
            .AppendLine()
            .Append("    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ")
            .Append(modelType)
            .AppendLine(" value, global::System.Text.Json.JsonSerializerOptions options)")
            .AppendLine("        => global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);")
            .AppendLine("}");
        return sourceBuilder.ToString();
    }

    private static string OpenGenericType(string name, int arity)
        => name + "<" + new string(',', arity - 1) + ">";

    private static void EmitObjectModel(
        StringBuilder source,
        GenerationContext generation,
        string declarationName,
        string generatedName,
        JsonElement objectType,
        IReadOnlyList<string> typeParameters)
    {
        var properties = objectType.GetProperty("properties");
        var usedPropertyNames = new HashSet<string>(StringComparer.Ordinal);
        var hasIndexSignatures =
            objectType.TryGetProperty("indexSignatures", out var indexes)
            && indexes.GetArrayLength() > 0;
        ObjectModelIndex? mappedIndex = null;
        if (hasIndexSignatures)
        {
            usedPropertyNames.Add("AdditionalProperties");
        }
        var mappedProperties = new List<ObjectModelProperty>();
        var previousTypeParameterMappings =
            generation.ActiveTypeParameterMappings;
        generation.ActiveTypeParameterMappings = typeParameters.ToDictionary(
            static parameter => parameter,
            static parameter => new TypeMapping(
                EscapeIdentifier(parameter),
                IsBinding: false,
                WireCSharpType: EscapeIdentifier(parameter + "Wire"),
                FromWireTemplate:
                    "convert"
                    + PascalCase(parameter)
                    + "(__VALUE__)"),
            StringComparer.Ordinal);
        try
        {
            foreach (var property in properties.EnumerateArray())
            {
                var javascriptName = property.GetProperty("name").GetString()!;
                var propertyName = PascalCase(javascriptName);
                if (propertyName.Length == 0)
                {
                    propertyName = "Value";
                }
                if (string.Equals(propertyName, generatedName, StringComparison.Ordinal))
                {
                    propertyName += "Value";
                }
                if (propertyName is "Equals" or "GetHashCode" or "GetType"
                    or "MemberwiseClone" or "ReferenceEquals" or "ToString")
                {
                    propertyName += "Value";
                }
                var preferredPropertyName = propertyName;
                for (var suffix = 2; !usedPropertyNames.Add(propertyName); suffix++)
                {
                    propertyName = preferredPropertyName + suffix;
                }
                var optional = property.GetProperty("optional").GetBoolean();
                var propertyType = property.GetProperty("type");
                var mapping = MapOptionalParameterType(
                    generation,
                    propertyType,
                    optional,
                    $"{generatedName}.{propertyName}");
                if (optional)
                {
                    mapping = MapOptionalModelProperty(mapping);
                }
                mappedProperties.Add(new ObjectModelProperty(
                    javascriptName,
                    propertyName,
                    optional,
                    mapping,
                    propertyType.Clone()));
            }
            if (hasIndexSignatures)
            {
                var signatures = indexes.EnumerateArray().ToArray();
                var signature = signatures.FirstOrDefault(candidate =>
                    string.Equals(
                        candidate.GetProperty("key").GetString(),
                        "string",
                        StringComparison.Ordinal));
                if (signature.ValueKind == JsonValueKind.Undefined)
                {
                    signature = signatures[0];
                }
                var numericKey = string.Equals(
                    signature.GetProperty("key").GetString(),
                    "number",
                    StringComparison.Ordinal);
                mappedIndex = new ObjectModelIndex(
                    numericKey ? "double" : "string",
                    numericKey,
                    MapType(
                        generation,
                        signature.GetProperty("value"),
                        optional: false,
                        $"{generatedName} index value"));
            }
        }
        finally
        {
            generation.ActiveTypeParameterMappings =
                previousTypeParameterMappings;
        }

        var genericSuffix = declarationName.Substring(generatedName.Length);
        var wireTypeParameters = typeParameters
            .Select(static parameter => EscapeIdentifier(parameter + "Wire"))
            .ToArray();
        var wireGenericSuffix = wireTypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", wireTypeParameters) + ">";
        var wireDeclarationName =
            generatedName + "Wire" + wireGenericSuffix;
        if (mappedIndex is not null)
        {
            source.Append("[global::System.Text.Json.Serialization.JsonConverter(typeof(")
                .Append(generatedName)
                .Append(typeParameters.Count == 0
                    ? "JsonConverter"
                    : "JsonConverterFactory")
                .AppendLine("))]");
        }
        source.Append("public sealed record ").Append(declarationName)
            .AppendLine()
            .AppendLine("{");
        foreach (var property in mappedProperties)
        {
            source.Append("    [global::System.Text.Json.Serialization.JsonPropertyName(")
                .Append(Literal(property.JavaScriptName)).AppendLine(")]");
            if (property.Optional)
            {
                source.AppendLine("    [global::System.Text.Json.Serialization.JsonIgnore(Condition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]");
            }
            source
                .Append("    public ");
            if (!property.Optional && !IsValueType(property.Mapping.CSharpType))
            {
                source.Append("required ");
            }
            source.Append(property.Mapping.CSharpType).Append(' ')
                .Append(EscapeIdentifier(property.CSharpName))
                .Append(" { get; init; }");
            if (property.Optional || IsValueType(property.Mapping.CSharpType))
            {
                source.Append(" = default;");
            }
            source.AppendLine().AppendLine();
        }
        if (mappedIndex is { } typedIndex)
        {
            source.Append("    public global::System.Collections.Generic.IReadOnlyDictionary<")
                .Append(typedIndex.KeyType).Append(", ")
                .Append(typedIndex.ValueMapping.CSharpType)
                .AppendLine(">? AdditionalProperties { get; init; }")
                .AppendLine();
        }
        source.Append("    internal static ").Append(declarationName)
            .Append(" FromWire");
        if (wireTypeParameters.Length > 0)
        {
            source.Append(wireGenericSuffix);
        }
        source.Append('(').Append(wireDeclarationName)
            .Append(" wire, global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker");
        for (var index = 0; index < typeParameters.Count; index++)
        {
            source.Append(", global::System.Func<")
                .Append(wireTypeParameters[index]).Append(", ")
                .Append(EscapeIdentifier(typeParameters[index]))
                .Append("> convert")
                .Append(PascalCase(typeParameters[index]));
        }
        source.AppendLine(")")
            .AppendLine("        => new()")
            .AppendLine("        {");
        foreach (var property in mappedProperties)
        {
            var propertyName = EscapeIdentifier(property.CSharpName);
            var conversion = property.Mapping.ConvertFromWire(
                "wire." + propertyName,
                "invoker");
            if (property.Mapping.RequiresWireConversion)
            {
                conversion =
                    "((global::System.Func<"
                    + property.Mapping.CSharpType
                    + ">)(() => "
                    + conversion
                    + "))()";
            }
            source.Append("            ").Append(propertyName).Append(" = ")
                .Append(conversion)
                .AppendLine(",");
        }
        if (mappedIndex is { } indexMapping)
        {
            var wireValue =
                "global::WebScene.JavaScript.Interop.JavaScriptInteropSerializer.Deserialize<"
                + indexMapping.ValueMapping.EffectiveWireCSharpType
                + ">(pair.Value)";
            var convertedValue = indexMapping.ValueMapping.ConvertFromWire(
                wireValue,
                "invoker");
            if (indexMapping.ValueMapping.RequiresWireConversion)
            {
                convertedValue =
                    "((global::System.Func<"
                    + indexMapping.ValueMapping.CSharpType
                    + ">)(() => "
                    + convertedValue
                    + "))()";
            }
            var convertedKey = indexMapping.NumericKey
                ? "double.Parse(pair.Key, global::System.Globalization.CultureInfo.InvariantCulture)"
                : "pair.Key";
            source.AppendLine("            AdditionalProperties = wire.AdditionalProperties is { } additionalProperties")
                .AppendLine("                ? global::System.Linq.Enumerable.ToDictionary(")
                .AppendLine("                    additionalProperties,")
                .Append("                    pair => ").Append(convertedKey).AppendLine(",")
                .Append("                    pair => ").Append(convertedValue).AppendLine(")")
                .AppendLine("                : null,");
        }
        source.AppendLine("        };");
        if (typeParameters.Count == 0
            && mappedIndex is null
            && mappedProperties.All(property =>
                CanEmitBinaryType(generation, property.Type)))
        {
            EmitObjectModelBinaryCodec(
                source,
                generation,
                declarationName,
                mappedProperties);
        }
        source.AppendLine("}")
            .AppendLine()
            .Append("internal sealed record ").Append(wireDeclarationName)
            .AppendLine()
            .AppendLine("{");
        foreach (var property in mappedProperties)
        {
            var wireType = property.Mapping.EffectiveWireCSharpType;
            source.Append("    [global::System.Text.Json.Serialization.JsonPropertyName(")
                .Append(Literal(property.JavaScriptName)).AppendLine(")]");
            if (property.Optional)
            {
                source.AppendLine("    [global::System.Text.Json.Serialization.JsonIgnore(Condition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]");
            }
            source
                .Append("    public ");
            if (!property.Optional && !IsValueType(wireType))
            {
                source.Append("required ");
            }
            source.Append(wireType).Append(' ')
                .Append(EscapeIdentifier(property.CSharpName))
                .Append(" { get; init; }");
            if (property.Optional || IsValueType(wireType))
            {
                source.Append(" = default;");
            }
            source.AppendLine().AppendLine();
        }
        if (hasIndexSignatures)
        {
            source.AppendLine("    [global::System.Text.Json.Serialization.JsonExtensionData]")
                .AppendLine("    public global::System.Collections.Generic.IDictionary<string, global::System.Text.Json.JsonElement>? AdditionalProperties { get; init; }")
                .AppendLine();
        }
        source.AppendLine("}");
        if (mappedIndex is { } converterIndex)
        {
            EmitIndexedModelJsonConverter(
                source,
                declarationName,
                generatedName,
                typeParameters,
                mappedProperties,
                converterIndex);
        }
    }

    private static void EmitObjectModelBinaryCodec(
        StringBuilder source,
        GenerationContext generation,
        string declarationName,
        IReadOnlyList<ObjectModelProperty> properties)
    {
        var requiredCount = properties.Count(static property => !property.Optional);
        source.AppendLine()
            .AppendLine("    internal static uint __WebSceneWriteBinary(")
            .AppendLine("        ref global::WebScene.JavaScript.Interop.JavaScriptBinaryWriter writer,")
            .Append("        ").Append(declarationName).AppendLine(" value)")
            .AppendLine("    {")
            .AppendLine("        global::System.ArgumentNullException.ThrowIfNull(value);")
            .Append("        var propertyCount = ").Append(requiredCount)
            .AppendLine(";");
        foreach (var property in properties.Where(static property => property.Optional))
        {
            source.Append("        if (value.")
                .Append(EscapeIdentifier(property.CSharpName))
                .AppendLine(".HasValue) propertyCount++;");
        }
        source.AppendLine("        var result = writer.BeginObject(propertyCount);")
            .AppendLine("        var propertyIndex = 0;");
        foreach (var property in properties)
        {
            var propertyName = EscapeIdentifier(property.CSharpName);
            var valueType = property.Optional
                ? OptionalBinaryPayloadType(property.Type)
                : property.Type;
            if (property.Optional)
            {
                source.Append("        if (value.").Append(propertyName)
                    .AppendLine(".HasValue)")
                    .AppendLine("        {");
            }
            var indent = property.Optional ? "            " : "        ";
            var value = EmitBinaryWriteValue(
                source,
                generation,
                valueType,
                "value." + propertyName + (property.Optional ? ".Value!" : string.Empty),
                indent);
            source.Append(indent).Append("writer.SetObjectProperty(result, propertyIndex++, ")
                .Append(Literal(property.JavaScriptName)).Append("u8, ")
                .Append(value).AppendLine(");");
            if (property.Optional)
            {
                source.AppendLine("        }");
            }
        }
        source.AppendLine("        return result;")
            .AppendLine("    }")
            .AppendLine()
            .Append("    internal static ").Append(declarationName)
            .AppendLine(" __WebSceneReadBinary(")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryValue value,")
            .AppendLine("        global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker)")
            .AppendLine("    {");

        var values = new List<(ObjectModelProperty Property, string Local)>();
        foreach (var property in properties)
        {
            if (!property.Optional)
            {
                var local = EmitBinaryReadValue(
                    source,
                    generation,
                    property.Type,
                    "value.GetRequiredProperty(" + Literal(property.JavaScriptName) + "u8)",
                    "invoker",
                    "        ");
                values.Add((property, local));
                continue;
            }

            var optionalType = property.Mapping.CSharpType;
            var node = generation.NextLocal("binaryProperty");
            var localOptional = generation.NextLocal("binaryOptional");
            source.Append("        ").Append(optionalType).Append(' ')
                .Append(localOptional).AppendLine(";")
                .Append("        if (value.TryGetProperty(")
                .Append(Literal(property.JavaScriptName)).Append("u8, out var ")
                .Append(node).AppendLine(")")
                .Append("            && ").Append(node)
                .AppendLine(".Kind != global::WebScene.JavaScript.Interop.JavaScriptBinaryValueKind.Undefined)")
                .AppendLine("        {");
            var child = EmitBinaryReadValue(
                source,
                generation,
                OptionalBinaryPayloadType(property.Type),
                node,
                "invoker",
                "            ");
            source.Append("            ").Append(localOptional).Append(" = ")
                .Append(child).AppendLine(";")
                .AppendLine("        }")
                .AppendLine("        else")
                .AppendLine("        {")
                .Append("            ").Append(localOptional)
                .AppendLine(" = default;")
                .AppendLine("        }");
            values.Add((property, localOptional));
        }
        source.AppendLine("        return new()")
            .AppendLine("        {");
        foreach (var (property, local) in values)
        {
            source.Append("            ")
                .Append(EscapeIdentifier(property.CSharpName))
                .Append(" = ").Append(local).AppendLine(",");
        }
        source.AppendLine("        };")
            .AppendLine("    }");
    }

    private static JsonElement OptionalBinaryPayloadType(JsonElement type)
    {
        if (Kind(type) != "union")
        {
            return type;
        }
        var candidates = FlattenUnionTypes(type)
            .Where(static candidate => Kind(candidate) != "undefined")
            .ToArray();
        if (candidates.Length == 1)
        {
            return candidates[0];
        }
        return type;
    }

    private static void EmitIndexedModelJsonConverter(
        StringBuilder source,
        string declarationName,
        string generatedName,
        IReadOnlyList<string> typeParameters,
        IReadOnlyList<ObjectModelProperty> properties,
        ObjectModelIndex index)
    {
        var escapedTypeParameters = typeParameters.Select(EscapeIdentifier).ToArray();
        var genericSuffix = escapedTypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", escapedTypeParameters) + ">";
        if (escapedTypeParameters.Length > 0)
        {
            source.AppendLine()
                .Append("public sealed class ").Append(generatedName)
                .AppendLine("JsonConverterFactory : global::System.Text.Json.Serialization.JsonConverterFactory")
                .AppendLine("{")
                .AppendLine("    public override bool CanConvert(global::System.Type typeToConvert)")
                .Append("        => typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof(")
                .Append(OpenGenericType(generatedName, escapedTypeParameters.Length))
                .AppendLine(");")
                .AppendLine()
                .AppendLine("    public override global::System.Text.Json.Serialization.JsonConverter CreateConverter(")
                .AppendLine("        global::System.Type typeToConvert,")
                .AppendLine("        global::System.Text.Json.JsonSerializerOptions options)")
                .Append("        => (global::System.Text.Json.Serialization.JsonConverter)global::System.Activator.CreateInstance(typeof(")
                .Append(OpenGenericType(
                    generatedName + "JsonConverter",
                    escapedTypeParameters.Length))
                .AppendLine(").MakeGenericType(typeToConvert.GetGenericArguments()))!;")
                .AppendLine("}");
        }
        source.AppendLine()
            .Append("public sealed class ").Append(generatedName)
            .Append("JsonConverter").Append(genericSuffix)
            .Append(" : global::System.Text.Json.Serialization.JsonConverter<")
            .Append(declarationName).AppendLine(">")
            .AppendLine("{")
            .Append("    public override ").Append(declarationName)
            .AppendLine(" Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)")
            .AppendLine("        => throw new global::System.NotSupportedException(\"Indexed JavaScript models are materialized through their generated native-engine binding.\");")
            .AppendLine()
            .Append("    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ")
            .Append(declarationName)
            .AppendLine(" value, global::System.Text.Json.JsonSerializerOptions options)")
            .AppendLine("    {")
            .AppendLine("        writer.WriteStartObject();");
        foreach (var property in properties)
        {
            var propertyAccess = "value." + EscapeIdentifier(property.CSharpName);
            if (property.Optional)
            {
                source.Append("        if (").Append(propertyAccess).AppendLine(".HasValue)")
                    .AppendLine("        {")
                    .Append("            writer.WritePropertyName(")
                    .Append(Literal(property.JavaScriptName)).AppendLine(");")
                    .Append("            global::System.Text.Json.JsonSerializer.Serialize(writer, ")
                    .Append(propertyAccess).AppendLine(".Value, options);")
                    .AppendLine("        }");
            }
            else
            {
                source.Append("        writer.WritePropertyName(")
                    .Append(Literal(property.JavaScriptName)).AppendLine(");")
                    .Append("        global::System.Text.Json.JsonSerializer.Serialize(writer, ")
                    .Append(propertyAccess).AppendLine(", options);");
            }
        }
        source.AppendLine("        if (value.AdditionalProperties is { } additionalProperties)")
            .AppendLine("        {")
            .AppendLine("            foreach (var pair in additionalProperties)")
            .AppendLine("            {");
        if (!index.NumericKey && properties.Count > 0)
        {
            source.Append("                if (");
            for (var propertyIndex = 0; propertyIndex < properties.Count; propertyIndex++)
            {
                if (propertyIndex > 0)
                {
                    source.Append(" || ");
                }
                source.Append("pair.Key == ")
                    .Append(Literal(properties[propertyIndex].JavaScriptName));
            }
            source.AppendLine(")")
                .AppendLine("                {")
                .AppendLine("                    continue;")
                .AppendLine("                }");
        }
        source.Append("                writer.WritePropertyName(")
            .Append(index.NumericKey
                ? "pair.Key.ToString(global::System.Globalization.CultureInfo.InvariantCulture)"
                : "pair.Key")
            .AppendLine(");")
            .AppendLine("                global::System.Text.Json.JsonSerializer.Serialize(writer, pair.Value, options);")
            .AppendLine("            }")
            .AppendLine("        }")
            .AppendLine("        writer.WriteEndObject();")
            .AppendLine("    }")
            .AppendLine("}");
    }

    private static bool TryGetInlineObject(
        JsonElement type,
        out JsonElement inlineObject,
        out bool nullable)
    {
        if (Kind(type) == "inlineObject")
        {
            inlineObject = type;
            nullable = false;
            return true;
        }
        if (Kind(type) == "union")
        {
            var candidates = type.GetProperty("types").EnumerateArray().ToArray();
            var concrete = candidates
                .Where(candidate => Kind(candidate) is not ("undefined" or "null"))
                .ToArray();
            if (concrete.Length == 1 && Kind(concrete[0]) == "inlineObject")
            {
                inlineObject = concrete[0];
                nullable = concrete.Length != candidates.Length;
                return true;
            }
        }
        inlineObject = default;
        nullable = false;
        return false;
    }

    private static string GenerateEnumModel(string namespaceName, Model model)
    {
        var members = model.Type.TryGetProperty("enumMembers", out var enumMembers)
            ? enumMembers.EnumerateArray().ToArray()
            : [];
        var isString = members.Any(member =>
            member.TryGetProperty("value", out var value)
            && value.ValueKind == JsonValueKind.String);
        if (isString)
        {
            var syntheticUnion = JsonDocument.Parse(
                "{\"kind\":\"union\",\"types\":["
                + string.Join(",", members.Select(member =>
                    "{\"kind\":\"literal\",\"value\":"
                    + JsonSerializer.Serialize(member.GetProperty("value").GetString())
                    + "}"))
                + "]}");
            using (syntheticUnion)
            {
                return GenerateStringUnionModel(
                    namespaceName,
                    model,
                    syntheticUnion.RootElement);
            }
        }

        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        source.Append("namespace ").Append(namespaceName).AppendLine(";")
            .AppendLine()
            .Append("public enum ").Append(model.Name).AppendLine()
            .AppendLine("{");
        for (var index = 0; index < members.Length; index++)
        {
            var member = members[index];
            source.Append("    ").Append(EscapeIdentifier(
                PascalCase(member.GetProperty("name").GetString()!)));
            if (member.TryGetProperty("value", out var value)
                && value.ValueKind == JsonValueKind.Number)
            {
                source.Append(" = ").Append(value.GetRawText());
            }
            source.AppendLine(index == members.Length - 1 ? string.Empty : ",");
        }
        return source.AppendLine("}").ToString();
    }

    private static string GenerateStringUnionModel(
        string namespaceName,
        Model model,
        JsonElement union)
    {
        var values = union.GetProperty("types")
            .EnumerateArray()
            .Where(static candidate =>
                Kind(candidate) == "literal"
                && candidate.GetProperty("value").ValueKind == JsonValueKind.String)
            .Select(static candidate => candidate.GetProperty("value").GetString()!)
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        source.Append("namespace ").Append(namespaceName).AppendLine(";")
            .AppendLine()
            .Append("[global::System.Text.Json.Serialization.JsonConverter(typeof(")
            .Append(model.Name).AppendLine("JsonConverter))]")
            .Append("public readonly record struct ").Append(model.Name)
            .AppendLine("(string Value)")
            .AppendLine("{");
        foreach (var value in values)
        {
            source.Append("    public static ").Append(model.Name).Append(' ')
                .Append(EscapeIdentifier(PascalCase(value)))
                .Append(" { get; } = new(").Append(Literal(value)).AppendLine(");");
        }
        source.AppendLine()
            .Append("    public static implicit operator string(").Append(model.Name)
            .AppendLine(" value) => value.Value;")
            .Append("    public static implicit operator ").Append(model.Name)
            .AppendLine("(string value) => new(value);")
            .AppendLine("    public override string ToString() => Value;")
            .AppendLine("}")
            .AppendLine()
            .Append("public sealed class ").Append(model.Name)
            .Append("JsonConverter : global::System.Text.Json.Serialization.JsonConverter<")
            .Append(model.Name).AppendLine(">")
            .AppendLine("{")
            .Append("    public override ").Append(model.Name)
            .AppendLine(" Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)")
            .Append("        => new(reader.GetString() ?? throw new global::System.Text.Json.JsonException(")
            .Append(Literal($"Expected a string for {model.Name}.")).AppendLine("));")
            .AppendLine()
            .Append("    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ")
            .Append(model.Name)
            .AppendLine(" value, global::System.Text.Json.JsonSerializerOptions options)")
            .AppendLine("        => writer.WriteStringValue(value.Value);")
            .AppendLine("}");
        return source.ToString();
    }

}
