using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace WebScene.JavaScript.Interop.Generator;

public sealed partial class ManifestJavaScriptBindingGenerator
{
    private static string GenerateBinding(
        GenerationContext generation,
        Binding binding,
        string policyPath)
    {
        var selfType = BindingTypeName(binding);
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            """);
        source.Append("namespace ").Append(generation.Namespace).AppendLine(";")
            .AppendLine()
            .Append("public sealed class ").Append(selfType)
            .AppendLine(" : global::WebScene.JavaScript.Interop.IJavaScriptObjectReferenceProvider, global::System.IAsyncDisposable")
            .AppendLine("{")
            .AppendLine("    private readonly global::WebScene.JavaScript.Interop.IJavaScriptInvoker __webSceneInvoker;")
            .AppendLine("    private readonly global::WebScene.JavaScript.Interop.JavaScriptObjectReference __webSceneReference;")
            .AppendLine()
            .Append("    internal ").Append(binding.Name)
            .AppendLine("(global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker, global::WebScene.JavaScript.Interop.JavaScriptObjectReference reference)")
            .AppendLine("    {")
            .AppendLine("        __webSceneInvoker = invoker;")
            .AppendLine("        __webSceneReference = reference;")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    public global::WebScene.JavaScript.Interop.JavaScriptObjectReference JavaScriptReference => __webSceneReference;")
            .AppendLine("    internal global::WebScene.JavaScript.Interop.JavaScriptObjectReference __WebSceneReference => __webSceneReference;")
            .AppendLine()
            .AppendLine("    public global::System.Threading.Tasks.ValueTask DisposeAsync() => __webSceneInvoker.ReleaseAsync(__webSceneReference);");
        source.AppendLine()
            .Append("    public static ").Append(selfType).AppendLine(" FromReference(")
            .AppendLine("        global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker,")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptObjectReference reference)")
            .Append("        => new ").Append(selfType).AppendLine("(invoker, reference);");

        if (binding.Policy.TryGetProperty("constructors", out var constructors)
            && constructors.ValueKind == JsonValueKind.Array
            && constructors.GetArrayLength() > 0)
        {
            foreach (var constructor in constructors.EnumerateArray())
            {
                EmitConstructor(source, generation, binding, constructor, policyPath);
            }
        }
        else if (binding.Policy.TryGetProperty("constructor", out var constructor)
                 && constructor.ValueKind == JsonValueKind.Object)
        {
            EmitConstructor(source, generation, binding, constructor, policyPath);
        }

        if (binding.Policy.TryGetProperty("methods", out var methods))
        {
            foreach (var methodPolicy in methods.EnumerateArray())
            {
                if (methodPolicy.TryGetProperty("include", out var include)
                    && include.ValueKind == JsonValueKind.False)
                {
                    continue;
                }
                EmitMethod(
                    source,
                    generation,
                    binding,
                    methodPolicy,
                    policyPath);
            }
        }
        if (binding.Policy.TryGetProperty("properties", out var properties))
        {
            foreach (var propertyPolicy in properties.EnumerateArray())
            {
                if (propertyPolicy.TryGetProperty("include", out var include)
                    && include.ValueKind == JsonValueKind.False)
                {
                    continue;
                }
                EmitProperty(
                    source,
                    generation,
                    binding,
                    propertyPolicy,
                    policyPath);
            }
        }

        return source.AppendLine("}").ToString();
    }

    private static void EmitProperty(
        StringBuilder source,
        GenerationContext generation,
        Binding binding,
        JsonElement propertyPolicy,
        string policyPath)
    {
        var memberName = RequiredString(propertyPolicy, "source", policyPath);
        var property = binding.Root.GetProperty("properties")
            .EnumerateArray()
            .FirstOrDefault(candidate => string.Equals(
                candidate.GetProperty("name").GetString(),
                memberName,
                StringComparison.Ordinal));
        if (property.ValueKind == JsonValueKind.Undefined)
        {
            throw new InvalidDataException(
                $"Property '{binding.Source}.{memberName}' was not discovered.");
        }
        var getterName = OptionalString(propertyPolicy, "getterName")
                         ?? "Get" + PascalCase(memberName) + "Async";
        var declaredType = property.GetProperty("type");
        var promise = IsPromiseLikeReturn(declaredType);
        var effectiveType = Kind(declaredType) == "promise"
            ? declaredType.GetProperty("result")
            : declaredType;
        var mapping = MapType(
            generation,
            effectiveType,
            property.GetProperty("optional").GetBoolean(),
            $"{binding.Name}.{getterName}");
        var valueInvocation = promise
            ? "GetPromisePropertyAsync"
            : "GetPropertyAsync";
        var objectInvocation = promise
            ? "GetPromiseObjectPropertyAsync"
            : "GetObjectPropertyAsync";
        var binarySupported = CanEmitBinaryType(generation, effectiveType);
        var binaryName = "__WebSceneBinary"
                         + PascalCase(getterName)
                         + "Property";
        source.AppendLine()
            .Append("    public ");
        if (!binarySupported)
        {
            source.Append("async ");
        }
        source.Append("global::System.Threading.Tasks.ValueTask<")
            .Append(mapping.CSharpType).Append("> ").Append(getterName).AppendLine("(")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {");
        if (binarySupported)
        {
            source.AppendLine("        var binaryInvoker = __webSceneInvoker as global::WebScene.JavaScript.Interop.IJavaScriptBinaryInvoker")
                .AppendLine("            ?? throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        if (!binaryInvoker.IsBinaryInteropAvailable)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        }")
                .Append("        return binaryInvoker.InvokeBinaryAsync<global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid, ")
                .Append(mapping.CSharpType).Append(", ").Append(binaryName)
                .Append("Codec>(").Append(binaryName)
                .AppendLine("CallSite, __webSceneReference, new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid(), cancellationToken);")
                .AppendLine("    }");
            EmitBinaryInvocationCodec(
                source,
                generation,
                parameters: [],
                returnsVoid: false,
                effectiveReturn: effectiveType,
                returnMapping: mapping,
                binaryName: binaryName,
                operation: "GetProperty",
                globalName: null,
                memberName: memberName,
                promise: promise);
        }
        else if (mapping.IsBinding && mapping.IsNullable)
        {
            source.Append("        var reference = await __webSceneInvoker.")
                .Append(valueInvocation)
                .Append("<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append("__webSceneReference, ").Append(Literal(memberName))
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .Append("        return reference is { } value ? new ")
                .Append(mapping.NonNullableCSharpType)
                .AppendLine("(__webSceneInvoker, value) : null;");
        }
        else if (mapping.IsBinding)
        {
            source.Append("        return new ").Append(mapping.CSharpType)
                .Append("(__webSceneInvoker, await __webSceneInvoker.")
                .Append(objectInvocation).Append('(')
                .Append("__webSceneReference, ").Append(Literal(memberName))
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (mapping.IsFunctionReference && mapping.IsNullable)
        {
            source.Append("        var reference = await __webSceneInvoker.")
                .Append(valueInvocation)
                .Append("<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append("__webSceneReference, ").Append(Literal(memberName))
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .AppendLine("        return reference is { } value")
                .AppendLine("            ? new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(__webSceneInvoker, value)")
                .AppendLine("            : null;");
        }
        else if (mapping.IsFunctionReference)
        {
            source.Append("        return new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(__webSceneInvoker, await __webSceneInvoker.")
                .Append(objectInvocation).Append('(')
                .Append("__webSceneReference, ").Append(Literal(memberName))
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (mapping.IsObjectReference && !mapping.IsNullable)
        {
            source.Append("        return await __webSceneInvoker.")
                .Append(objectInvocation).Append('(')
                .Append("__webSceneReference, ").Append(Literal(memberName))
                .AppendLine(", cancellationToken).ConfigureAwait(false);");
        }
        else if (mapping.RequiresWireConversion)
        {
            source.Append("        var wire = (await __webSceneInvoker.")
                .Append(valueInvocation).Append('<')
                .Append(mapping.EffectiveWireCSharpType)
                .Append(">(__webSceneReference, ").Append(Literal(memberName))
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;")
                .Append("        return ")
                .Append(mapping.ConvertFromWire("wire", "__webSceneInvoker"))
                .AppendLine(";");
        }
        else
        {
            source.Append("        return (await __webSceneInvoker.")
                .Append(valueInvocation).Append('<')
                .Append(mapping.CSharpType).Append(">(__webSceneReference, ")
                .Append(Literal(memberName))
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;");
        }
        if (!binarySupported)
        {
            source.AppendLine("    }");
        }

        var writable = !property.GetProperty("readonly").GetBoolean()
                       && (!propertyPolicy.TryGetProperty("write", out var write)
                           || write.ValueKind != JsonValueKind.False);
        if (!writable)
        {
            return;
        }
        var setterName = OptionalString(propertyPolicy, "setterName")
                         ?? "Set" + PascalCase(memberName) + "Async";
        var setterMapping = promise
            ? new TypeMapping(
                "global::WebScene.JavaScript.Interop.JavaScriptObjectReference",
                IsBinding: false,
                IsObjectReference: true)
            : mapping;
        var binarySetterSupported =
            !promise
            && !property.GetProperty("optional").GetBoolean()
            && (CanEmitBinaryType(generation, effectiveType)
                || setterMapping.IsObjectReferenceProvider);
        var binarySetterName = "__WebSceneBinary"
                               + PascalCase(setterName)
                               + "Property";
        source.AppendLine()
            .Append("    public global::System.Threading.Tasks.ValueTask ")
            .Append(setterName).AppendLine("(")
            .Append("        ").Append(setterMapping.CSharpType).AppendLine(" value,")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {");
        if (binarySetterSupported)
        {
            source.AppendLine("        var binaryInvoker = __webSceneInvoker as global::WebScene.JavaScript.Interop.IJavaScriptBinaryInvoker")
                .AppendLine("            ?? throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        if (!binaryInvoker.IsBinaryInteropAvailable)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        }")
                .Append("        return binaryInvoker.InvokeBinaryVoidAsync<")
                .Append(binarySetterName).Append("Arguments, ")
                .Append(binarySetterName).Append("Codec>(")
                .Append(binarySetterName)
                .Append("CallSite, __webSceneReference, new ")
                .Append(binarySetterName)
                .AppendLine("Arguments(value), cancellationToken);")
                .AppendLine("    }");
            EmitBinaryInvocationCodec(
                source,
                generation,
                parameters:
                [
                    new MappedParameter(
                        "value",
                        setterMapping,
                        Optional: false,
                        Rest: false,
                        effectiveType.Clone())
                ],
                returnsVoid: true,
                effectiveReturn: effectiveType,
                returnMapping: new TypeMapping("void", false),
                binaryName: binarySetterName,
                operation: "SetProperty",
                globalName: null,
                memberName: memberName,
                promise: false);
            return;
        }
        source.AppendLine("        return __webSceneInvoker.SetPropertyAsync(")
            .AppendLine("            __webSceneReference,")
            .Append("            ").Append(Literal(memberName)).AppendLine(",")
            .Append("            ");
        if (setterMapping.IsBinding && setterMapping.IsNullable)
        {
            source.AppendLine("value is null")
                .AppendLine("                ? global::WebScene.JavaScript.Interop.JavaScriptArgument.From<object?>(null)")
                .AppendLine("                : global::WebScene.JavaScript.Interop.JavaScriptArgument.From(value.__WebSceneReference),");
        }
        else
        {
            source.Append("global::WebScene.JavaScript.Interop.JavaScriptArgument.From(")
                .Append(setterMapping.IsBinding
                    ? "value.__WebSceneReference"
                    : "value")
                .AppendLine("),");
        }
        source
            .AppendLine("            cancellationToken);");
        source.AppendLine("    }");
    }

    private static void EmitConstructor(
        StringBuilder source,
        GenerationContext generation,
        Binding binding,
        JsonElement constructor,
        string policyPath)
    {
        var globalName = RequiredString(constructor, "globalName", policyPath);
        var methodName = OptionalString(constructor, "name") ?? "CreateAsync";
        ConstructorParameter[] parameters;
        if (constructor.TryGetProperty("parameters", out var parameterList))
        {
            parameters = parameterList.EnumerateArray()
                .Select(parameter => new ConstructorParameter(
                    RequiredString(parameter, "name", policyPath),
                    RequiredString(parameter, "dotnetType", policyPath),
                    IsBinding: false,
                    IsNullable: false,
                    Optional: false,
                    Rest: false,
                    BinaryMapping: null,
                    BinaryType: default))
                .ToArray();
        }
        else if (binding.Root.TryGetProperty("constructors", out var constructors)
                 && constructors.GetArrayLength() > 0)
        {
            var overload = constructor.TryGetProperty("overload", out var overloadValue)
                ? overloadValue.GetInt32()
                : 0;
            if ((uint)overload >= (uint)constructors.GetArrayLength())
            {
                throw new InvalidDataException(
                    $"Constructor overload {overload} for '{binding.Source}' was not discovered.");
            }
            parameters = constructors[overload].GetProperty("parameters")
                .EnumerateArray()
                .Select(parameter =>
                {
                    var name = parameter.GetProperty("name").GetString()!;
                    var optional = parameter.GetProperty("optional").GetBoolean();
                    var rest = parameter.GetProperty("rest").GetBoolean();
                    var mapping = MapOptionalParameterType(
                        generation,
                        parameter.GetProperty("type"),
                        optional,
                        $"{binding.Name}.{methodName} parameter '{name}'");
                    var typeName = optional
                        ? $"global::WebScene.JavaScript.Interop.JavaScriptOptional<{mapping.CSharpType}>"
                        : mapping.CSharpType;
                    return new ConstructorParameter(
                        name,
                        typeName,
                        mapping.IsBinding,
                        mapping.IsNullable,
                        optional,
                        rest,
                        mapping,
                        parameter.GetProperty("type").Clone());
                })
                .ToArray();
        }
        else
        {
            parameters = [];
        }
        var binarySupported = parameters.All(parameter =>
            !parameter.Rest
            && parameter.BinaryMapping is not null
            && CanEmitBinaryType(generation, parameter.BinaryType));
        var binaryName = "__WebSceneBinary"
                         + PascalCase(methodName)
                         + "Constructor";
        source.AppendLine()
            .Append("    public static ");
        if (!binarySupported)
        {
            source.Append("async ");
        }
        source.Append("global::System.Threading.Tasks.ValueTask<")
            .Append(BindingTypeName(binding)).Append("> ").Append(methodName).AppendLine("(")
            .AppendLine("        global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker,");
        for (var index = 0; index < parameters.Length; index++)
        {
            var parameter = parameters[index];
            source.Append("        ")
                .Append(parameter.CSharpType)
                .Append(" @")
                .Append(parameter.Name);
            if (parameter.Optional)
            {
                source.Append(" = default");
            }
            source.AppendLine(",");
        }
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {");
        if (binarySupported)
        {
            var binaryArgumentsType = parameters.Length == 0
                ? "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid"
                : binaryName + "Arguments";
            var binaryArguments = parameters.Length == 0
                ? "new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid()"
                : "new " + binaryName + "Arguments("
                  + string.Join(
                      ", ",
                      parameters.Select(parameter => "@" + parameter.Name))
                  + ")";
            source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(invoker);")
                .AppendLine("        var binaryInvoker = invoker as global::WebScene.JavaScript.Interop.IJavaScriptBinaryInvoker")
                .AppendLine("            ?? throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        if (!binaryInvoker.IsBinaryInteropAvailable)")
                .AppendLine("        {")
                .AppendLine("            throw new global::System.NotSupportedException(")
                .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
                .AppendLine("        }")
                .Append("        return binaryInvoker.InvokeBinaryAsync<")
                .Append(binaryArgumentsType).Append(", ")
                .Append(BindingTypeName(binding)).Append(", ")
                .Append(binaryName).Append("Codec>(")
                .Append(binaryName).Append("CallSite, default, ")
                .Append(binaryArguments).AppendLine(", cancellationToken);")
                .AppendLine("    }");
            EmitBinaryConstructorCodec(
                source,
                generation,
                binding,
                parameters,
                binaryName,
                globalName);
            return;
        }
        source.Append("        return new ").Append(BindingTypeName(binding))
            .AppendLine("(invoker, await invoker.ConstructAsync(")
            .Append("            ").Append(Literal(globalName)).AppendLine(",")
            .Append("            ").Append(ArgumentArray(
                parameters.Select(parameter => new Parameter(
                    parameter.Name,
                    parameter.IsBinding,
                    parameter.IsNullable,
                    parameter.Optional,
                    parameter.Rest)))).AppendLine(",")
            .AppendLine("            cancellationToken).ConfigureAwait(false));")
            .AppendLine("    }");
    }

    private static void EmitMethod(
        StringBuilder source,
        GenerationContext generation,
        Binding binding,
        JsonElement methodPolicy,
        string policyPath)
    {
        var memberName = RequiredString(methodPolicy, "source", policyPath);
        var overload = methodPolicy.TryGetProperty("overload", out var overloadValue)
            ? overloadValue.GetInt32()
            : 0;
        var method = binding.Root.GetProperty("methods")
            .EnumerateArray()
            .FirstOrDefault(candidate =>
                string.Equals(
                    candidate.GetProperty("name").GetString(),
                    memberName,
                    StringComparison.Ordinal)
                && candidate.GetProperty("overload").GetInt32() == overload);
        if (method.ValueKind == JsonValueKind.Undefined)
        {
            throw new InvalidDataException(
                $"Method '{binding.Source}.{memberName}' overload {overload} was not discovered.");
        }

        var methodName = OptionalString(methodPolicy, "name")
                         ?? PascalCase(memberName) + "Async";
        var borrowedName = OptionalString(methodPolicy, "borrowedName");
        var methodTypeParameters = method.TryGetProperty("typeParameters", out var genericParameters)
            ? genericParameters.EnumerateArray()
                .Select(static item => EscapeIdentifier(item.GetString()!))
                .ToArray()
            : [];
        var methodGenericSuffix = methodTypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", methodTypeParameters) + ">";
        var omitOptional = !methodPolicy.TryGetProperty(
                               "omitOptionalParameters",
                               out var omitValue)
                           || omitValue.ValueKind != JsonValueKind.False;
        var parameters = method.GetProperty("parameters")
            .EnumerateArray()
            .Where(parameter =>
                !omitOptional
                || !parameter.GetProperty("optional").GetBoolean())
            .Select(parameter =>
            {
                var name = parameter.GetProperty("name").GetString()!;
                var optional = parameter.GetProperty("optional").GetBoolean();
                var rest = parameter.GetProperty("rest").GetBoolean();
                var mapping = MapOptionalParameterType(
                    generation,
                    parameter.GetProperty("type"),
                    optional,
                    $"{binding.Name}.{methodName} parameter '{name}'");
                if (optional)
                {
                    mapping = mapping with
                    {
                        CSharpType =
                            $"global::WebScene.JavaScript.Interop.JavaScriptOptional<{mapping.CSharpType}>"
                    };
                }
                return new MappedParameter(
                    name,
                    mapping,
                    optional,
                    rest,
                    parameter.GetProperty("type").Clone());
            })
            .ToArray();

        var declaredReturn = method.GetProperty("returns");
        var promise = IsPromiseLikeReturn(declaredReturn);
        var effectiveReturn = Kind(declaredReturn) == "promise"
            ? declaredReturn.GetProperty("result")
            : declaredReturn;
        var returnsVoid = IsVoidLikeReturn(declaredReturn);
        var returnMapping = returnsVoid
            ? new TypeMapping("void", false)
            : MapType(
                generation,
                effectiveReturn,
                optional: false,
                $"{binding.Name}.{methodName} return");
        var binarySupported = methodTypeParameters.Length == 0
                              && parameters.All(parameter =>
                                  !parameter.Rest
                                  && CanEmitBinaryType(
                                      generation,
                                      parameter.Type))
                              && (returnsVoid
                                  || CanEmitBinaryType(
                                      generation,
                                      effectiveReturn));
        var binaryName = "__WebSceneBinary"
                         + PascalCase(memberName)
                         + overload;
        if (borrowedName is not null
            && (!binarySupported || Kind(effectiveReturn) != "array"))
        {
            throw new InvalidDataException(
                $"Borrowed method '{binding.Name}.{borrowedName}' requires a binary-supported array return type.");
        }

        source.AppendLine()
            .Append("    public ");
        if (!binarySupported)
        {
            source.Append("async ");
        }
        source.Append("global::System.Threading.Tasks.ValueTask");
        if (!returnsVoid)
        {
            source.Append('<').Append(returnMapping.CSharpType).Append('>');
        }
        source.Append(' ').Append(methodName).Append(methodGenericSuffix).AppendLine("(");
        foreach (var parameter in parameters)
        {
            source.Append("        ").Append(parameter.Mapping.CSharpType)
                .Append(" @").Append(parameter.Name);
            if (parameter.Optional)
            {
                source.Append(" = default");
            }
            source.AppendLine(",");
        }
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {");

        if (binarySupported)
        {
            EmitBinaryMethodDispatch(
                source,
                parameters,
                returnsVoid,
                returnMapping,
                binaryName);
            source.AppendLine("    }");
            EmitBinaryInvocationCodec(
                source,
                generation,
                parameters,
                returnsVoid,
                effectiveReturn,
                returnMapping,
                binaryName,
                operation: "InvokeMember",
                globalName: null,
                memberName: memberName,
                promise: promise);
            if (borrowedName is not null)
            {
                EmitBorrowedBinaryMethod(
                    source,
                    parameters,
                    borrowedName,
                    binaryName);
            }
            return;
        }

        var arguments = ArgumentArray(parameters.Select(parameter =>
            new Parameter(
                parameter.Name,
                parameter.Mapping.IsBinding,
                parameter.Mapping.IsNullable,
                parameter.Optional,
                parameter.Rest)));
        if (promise)
        {
            if (returnsVoid)
            {
                source.Append("        await __webSceneInvoker.InvokePromiseAsync<global::System.Text.Json.JsonElement>(")
                    .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);");
            }
            else if (returnMapping.IsBinding && returnMapping.IsNullable)
            {
                source.Append("        var reference = await __webSceneInvoker.InvokePromiseAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                    .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);")
                    .Append("        return reference is { } value ? new ")
                    .Append(returnMapping.NonNullableCSharpType)
                    .AppendLine("(__webSceneInvoker, value) : null;");
            }
            else if (returnMapping.IsBinding)
            {
                source.Append("        return new ").Append(returnMapping.CSharpType)
                    .Append("(__webSceneInvoker, await __webSceneInvoker.InvokePromiseObjectAsync(")
                    .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false));");
            }
            else if (returnMapping.IsFunctionReference && returnMapping.IsNullable)
            {
                source.Append("        var reference = await __webSceneInvoker.InvokePromiseAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                    .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);")
                    .AppendLine("        return reference is { } value")
                    .AppendLine("            ? new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(__webSceneInvoker, value)")
                    .AppendLine("            : null;");
            }
            else if (returnMapping.IsFunctionReference)
            {
                source.Append("        return new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(__webSceneInvoker, await __webSceneInvoker.InvokePromiseObjectAsync(")
                    .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false));");
            }
            else if (returnMapping.IsObjectReference && !returnMapping.IsNullable)
            {
                source.Append("        return await __webSceneInvoker.InvokePromiseObjectAsync(")
                    .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                    .Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false);");
            }
            else if (returnMapping.RequiresWireConversion)
            {
                source.Append("        var wire = (await __webSceneInvoker.InvokePromiseAsync<")
                    .Append(returnMapping.EffectiveWireCSharpType)
                    .Append(">(__webSceneReference, ").Append(Literal(memberName))
                    .Append(", ").Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false))!;")
                    .Append("        return ")
                    .Append(returnMapping.ConvertFromWire(
                        "wire",
                        "__webSceneInvoker"))
                    .AppendLine(";");
            }
            else
            {
                source.Append("        return (await __webSceneInvoker.InvokePromiseAsync<")
                    .Append(returnMapping.CSharpType).Append(">(__webSceneReference, ")
                    .Append(Literal(memberName)).Append(", ").Append(arguments)
                    .AppendLine(", cancellationToken).ConfigureAwait(false))!;");
            }
        }
        else if (returnsVoid)
        {
            source.Append("        await __webSceneInvoker.InvokeVoidAsync(__webSceneReference, ")
                .Append(Literal(memberName)).Append(", ").Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);");
        }
        else if (returnMapping.IsBinding && returnMapping.IsNullable)
        {
            source.Append("        var reference = await __webSceneInvoker.InvokeAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .Append("        return reference is { } value ? new ")
                .Append(returnMapping.NonNullableCSharpType)
                .AppendLine("(__webSceneInvoker, value) : null;");
        }
        else if (returnMapping.IsBinding)
        {
            source.Append("        return new ").Append(returnMapping.CSharpType)
                .Append("(__webSceneInvoker, await __webSceneInvoker.InvokeObjectAsync(")
                .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (returnMapping.IsFunctionReference && returnMapping.IsNullable)
        {
            source.Append("        var reference = await __webSceneInvoker.InvokeAsync<global::WebScene.JavaScript.Interop.JavaScriptObjectReference?>(")
                .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);")
                .AppendLine("        return reference is { } value")
                .AppendLine("            ? new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(__webSceneInvoker, value)")
                .AppendLine("            : null;");
        }
        else if (returnMapping.IsFunctionReference)
        {
            source.Append("        return new global::WebScene.JavaScript.Interop.JavaScriptFunctionReference(__webSceneInvoker, await __webSceneInvoker.InvokeObjectAsync(")
                .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false));");
        }
        else if (returnMapping.IsObjectReference && !returnMapping.IsNullable)
        {
            source.Append("        return await __webSceneInvoker.InvokeObjectAsync(")
                .Append("__webSceneReference, ").Append(Literal(memberName)).Append(", ")
                .Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false);");
        }
        else if (returnMapping.RequiresWireConversion)
        {
            source.Append("        var wire = (await __webSceneInvoker.InvokeAsync<")
                .Append(returnMapping.EffectiveWireCSharpType)
                .Append(">(__webSceneReference, ").Append(Literal(memberName))
                .Append(", ").Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;")
                .Append("        return ")
                .Append(returnMapping.ConvertFromWire(
                    "wire",
                    "__webSceneInvoker"))
                .AppendLine(";");
        }
        else
        {
            source.Append("        return (await __webSceneInvoker.InvokeAsync<")
                .Append(returnMapping.CSharpType).Append(">(__webSceneReference, ")
                .Append(Literal(memberName)).Append(", ").Append(arguments)
                .AppendLine(", cancellationToken).ConfigureAwait(false))!;");
        }
        source.AppendLine("    }");
    }

    private static void EmitBorrowedBinaryMethod(
        StringBuilder source,
        IReadOnlyList<MappedParameter> parameters,
        string borrowedName,
        string binaryName)
    {
        var argumentsType = parameters.Count == 0
            ? "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid"
            : binaryName + "Arguments";
        var arguments = parameters.Count == 0
            ? "new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid()"
            : "new " + binaryName + "Arguments("
              + string.Join(
                  ", ",
                  parameters.Select(parameter => "@" + parameter.Name))
              + ")";
        var typeStem = borrowedName.EndsWith(
                "Async",
                StringComparison.Ordinal)
            ? borrowedName.Substring(0, borrowedName.Length - 5)
            : borrowedName;
        typeStem = PascalCase(typeStem);
        var leaseType = typeStem + "Lease";
        var viewType = typeStem + "View";

        source.AppendLine()
            .Append("    public async global::System.Threading.Tasks.ValueTask<")
            .Append(leaseType).Append("> ").Append(borrowedName)
            .AppendLine("(");
        foreach (var parameter in parameters)
        {
            source.Append("        ").Append(parameter.Mapping.CSharpType)
                .Append(" @").Append(parameter.Name);
            if (parameter.Optional)
            {
                source.Append(" = default");
            }
            source.AppendLine(",");
        }
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
            .AppendLine("    {")
            .AppendLine("        if (__webSceneInvoker is not global::WebScene.JavaScript.Interop.IJavaScriptBinaryInvoker binaryInvoker")
            .AppendLine("            || !binaryInvoker.IsBinaryInteropAvailable)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.NotSupportedException(")
            .AppendLine("                \"Borrowed JavaScript results require the native binary transport.\");")
            .AppendLine("        }")
            .Append("        return new ").Append(leaseType).AppendLine("(")
            .Append("            await binaryInvoker.InvokeBinaryBorrowedAsync<")
            .Append(argumentsType).Append(", ").Append(binaryName)
            .Append("Codec>(").Append(binaryName)
            .Append("CallSite, __webSceneReference, ")
            .Append(arguments)
            .AppendLine(", cancellationToken).ConfigureAwait(false));")
            .AppendLine("    }")
            .AppendLine()
            .Append("    public readonly struct ").Append(leaseType)
            .AppendLine(" : global::System.IDisposable")
            .AppendLine("    {")
            .AppendLine("        private readonly global::WebScene.JavaScript.Interop.JavaScriptBinaryResultLease? _lease;")
            .AppendLine()
            .Append("        internal ").Append(leaseType).AppendLine("(")
            .AppendLine("            global::WebScene.JavaScript.Interop.JavaScriptBinaryResultLease lease)")
            .AppendLine("        {")
            .AppendLine("            _lease = lease;")
            .AppendLine("        }")
            .AppendLine()
            .Append("        public ").Append(viewType).AppendLine(" Borrow()")
            .AppendLine("            => new((_lease ?? throw new global::System.InvalidOperationException(")
            .AppendLine("                \"The borrowed result lease is uninitialized.\")).Borrow());")
            .AppendLine()
            .AppendLine("        public void Dispose() => _lease?.Dispose();")
            .AppendLine("    }")
            .AppendLine()
            .Append("    public ref struct ").Append(viewType).AppendLine()
            .AppendLine("    {")
            .AppendLine("        private global::WebScene.JavaScript.Interop.JavaScriptBinaryBorrowScope _scope;")
            .AppendLine()
            .Append("        internal ").Append(viewType).AppendLine("(")
            .AppendLine("            global::WebScene.JavaScript.Interop.JavaScriptBinaryBorrowScope scope)")
            .AppendLine("        {")
            .AppendLine("            _scope = scope;")
            .AppendLine("            if (_scope.Root.Kind != global::WebScene.JavaScript.Interop.JavaScriptBinaryValueKind.Array)")
            .AppendLine("            {")
            .AppendLine("                _scope.Dispose();")
            .AppendLine("                throw new global::System.IO.InvalidDataException(")
            .AppendLine("                    \"The borrowed JavaScript result is not an array.\");")
            .AppendLine("            }")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        public readonly int Count => _scope.Root.Count;")
            .AppendLine()
            .AppendLine("        public readonly global::WebScene.JavaScript.Interop.JavaScriptBinaryValue this[int index]")
            .AppendLine("            => _scope.Root.GetArrayItem(index);")
            .AppendLine()
            .AppendLine("        public void Dispose() => _scope.Dispose();")
            .AppendLine("    }");
    }

    private static void EmitBinaryMethodDispatch(
        StringBuilder source,
        IReadOnlyList<MappedParameter> parameters,
        bool returnsVoid,
        TypeMapping returnMapping,
        string binaryName)
    {
        var argumentsType = parameters.Count == 0
            ? "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid"
            : binaryName + "Arguments";
        var arguments = parameters.Count == 0
            ? "new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid()"
            : "new " + binaryName + "Arguments("
              + string.Join(
                  ", ",
                  parameters.Select(parameter => "@" + parameter.Name))
              + ")";
        source.AppendLine("        var binaryInvoker = __webSceneInvoker as global::WebScene.JavaScript.Interop.IJavaScriptBinaryInvoker")
            .AppendLine("            ?? throw new global::System.NotSupportedException(")
            .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
            .AppendLine("        if (!binaryInvoker.IsBinaryInteropAvailable)")
            .AppendLine("        {")
            .AppendLine("            throw new global::System.NotSupportedException(")
            .AppendLine("                \"Generated JavaScript APIs require the binary ABI 3 transport.\");")
            .AppendLine("        }");
        if (returnsVoid)
        {
            source.Append("        return binaryInvoker.InvokeBinaryVoidAsync<")
                .Append(argumentsType).Append(", ").Append(binaryName)
                .Append("Codec>(").Append(binaryName)
                .Append("CallSite, __webSceneReference, ")
                .Append(arguments)
                .AppendLine(", cancellationToken);");
        }
        else
        {
            source.Append("        return binaryInvoker.InvokeBinaryAsync<")
                .Append(argumentsType).Append(", ")
                .Append(returnMapping.CSharpType).Append(", ")
                .Append(binaryName).Append("Codec>(")
                .Append(binaryName)
                .Append("CallSite, __webSceneReference, ")
                .Append(arguments)
                .AppendLine(", cancellationToken);");
        }
    }

    private static void EmitBinaryInvocationCodec(
        StringBuilder source,
        GenerationContext generation,
        IReadOnlyList<MappedParameter> parameters,
        bool returnsVoid,
        JsonElement effectiveReturn,
        TypeMapping returnMapping,
        string binaryName,
        string operation,
        string? globalName,
        string? memberName,
        bool promise)
    {
        var argumentsType = parameters.Count == 0
            ? "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid"
            : binaryName + "Arguments";
        var resultType = returnsVoid
            ? "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid"
            : returnMapping.CSharpType;
        var resultMode = returnsVoid
            ? "Void"
            : returnMapping.IsBinding
              || returnMapping.IsObjectReference
              || returnMapping.IsFunctionReference
                ? "RetainedHandle"
                : "Value";
        source.AppendLine()
            .Append("    private static readonly global::WebScene.JavaScript.Interop.JavaScriptBinaryCallSite ")
            .Append(binaryName).AppendLine("CallSite = new(")
            .Append("        global::WebScene.JavaScript.Interop.JavaScriptBinaryOperation.")
            .Append(operation).AppendLine(",")
            .Append("        globalName: ")
            .Append(globalName is null ? "null" : Literal(globalName))
            .AppendLine(",")
            .Append("        memberName: ")
            .Append(memberName is null ? "null" : Literal(memberName))
            .AppendLine(",")
            .Append("        global::WebScene.JavaScript.Interop.JavaScriptBinaryResultMode.")
            .Append(resultMode);
        if (promise)
        {
            source.AppendLine(",")
                .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryCallFlags.AwaitPromise);");
        }
        else
        {
            source.AppendLine(");");
        }

        if (parameters.Count > 0)
        {
            source.AppendLine()
                .Append("    private readonly record struct ")
                .Append(binaryName).AppendLine("Arguments(");
            for (var index = 0; index < parameters.Count; index++)
            {
                var parameter = parameters[index];
                source.Append("        ").Append(parameter.Mapping.CSharpType)
                    .Append(' ').Append(PascalCase(parameter.Name));
                source.AppendLine(index + 1 == parameters.Count ? ");" : ",");
            }
        }

        source.AppendLine()
            .Append("    private readonly struct ").Append(binaryName)
            .Append("Codec : global::WebScene.JavaScript.Interop.IJavaScriptBinaryCodec<")
            .Append(argumentsType).Append(", ").Append(resultType)
            .AppendLine(">")
            .AppendLine("    {")
            .AppendLine("        public static uint EncodeArguments(")
            .AppendLine("            ref global::WebScene.JavaScript.Interop.JavaScriptBinaryWriter writer,")
            .Append("            in ").Append(argumentsType)
            .AppendLine(" arguments)")
            .AppendLine("        {")
            .Append("            var root = writer.BeginArray(")
            .Append(parameters.Count).AppendLine(");");
        for (var index = 0; index < parameters.Count; index++)
        {
            var parameter = parameters[index];
            var expression =
                "arguments." + PascalCase(parameter.Name);
            string value;
            if (parameter.Optional)
            {
                value = generation.NextLocal("binaryArgument");
                source.Append("            uint ").Append(value)
                    .AppendLine(";")
                    .Append("            if (").Append(expression)
                    .AppendLine(".HasValue)")
                    .AppendLine("            {");
                var child = EmitBinaryWriteValue(
                    source,
                    generation,
                    OptionalBinaryPayloadType(parameter.Type),
                    expression + ".Value!",
                    "                ");
                source.Append("                ").Append(value).Append(" = ")
                    .Append(child).AppendLine(";")
                    .AppendLine("            }")
                    .AppendLine("            else")
                    .AppendLine("            {")
                    .Append("                ").Append(value)
                    .AppendLine(" = writer.WriteUndefined();")
                    .AppendLine("            }");
            }
            else
            {
                value = EmitBinaryWriteValue(
                    source,
                    generation,
                    parameter.Type,
                    expression,
                    "            ");
            }
            source.Append("            writer.SetArrayItem(root, ")
                .Append(index).Append(", ").Append(value).AppendLine(");");
        }
        source.AppendLine("            return root;")
            .AppendLine("        }")
            .AppendLine()
            .Append("        public static ").Append(resultType)
            .AppendLine(" DecodeResult(")
            .AppendLine("            global::WebScene.JavaScript.Interop.JavaScriptBinaryValue value,")
            .AppendLine("            global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker)")
            .AppendLine("        {");
        if (returnsVoid)
        {
            source.AppendLine("            return new global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid();");
        }
        else
        {
            var result = EmitBinaryReadValue(
                source,
                generation,
                effectiveReturn,
                "value",
                "invoker",
                "            ");
            source.Append("            return ").Append(result)
                .AppendLine(";");
        }
        source.AppendLine("        }")
            .AppendLine("    }");
    }

    private static void EmitBinaryConstructorCodec(
        StringBuilder source,
        GenerationContext generation,
        Binding binding,
        IReadOnlyList<ConstructorParameter> parameters,
        string binaryName,
        string globalName)
    {
        var argumentsType = parameters.Count == 0
            ? "global::WebScene.JavaScript.Interop.JavaScriptBinaryVoid"
            : binaryName + "Arguments";
        var resultType = BindingTypeName(binding);
        source.AppendLine()
            .Append("    private static readonly global::WebScene.JavaScript.Interop.JavaScriptBinaryCallSite ")
            .Append(binaryName).AppendLine("CallSite = new(")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryOperation.Construct,")
            .Append("        globalName: ").Append(Literal(globalName))
            .AppendLine(",")
            .AppendLine("        memberName: null,")
            .AppendLine("        global::WebScene.JavaScript.Interop.JavaScriptBinaryResultMode.RetainedHandle);");

        if (parameters.Count > 0)
        {
            source.AppendLine()
                .Append("    private readonly record struct ")
                .Append(binaryName).AppendLine("Arguments(");
            for (var index = 0; index < parameters.Count; index++)
            {
                var parameter = parameters[index];
                source.Append("        ").Append(parameter.CSharpType)
                    .Append(' ').Append(PascalCase(parameter.Name));
                source.AppendLine(index + 1 == parameters.Count ? ");" : ",");
            }
        }

        source.AppendLine()
            .Append("    private readonly struct ").Append(binaryName)
            .Append("Codec : global::WebScene.JavaScript.Interop.IJavaScriptBinaryCodec<")
            .Append(argumentsType).Append(", ").Append(resultType)
            .AppendLine(">")
            .AppendLine("    {")
            .AppendLine("        public static uint EncodeArguments(")
            .AppendLine("            ref global::WebScene.JavaScript.Interop.JavaScriptBinaryWriter writer,")
            .Append("            in ").Append(argumentsType)
            .AppendLine(" arguments)")
            .AppendLine("        {")
            .Append("            var root = writer.BeginArray(")
            .Append(parameters.Count).AppendLine(");");
        for (var index = 0; index < parameters.Count; index++)
        {
            var parameter = parameters[index];
            var expression = "arguments." + PascalCase(parameter.Name);
            string value;
            if (parameter.Optional)
            {
                value = generation.NextLocal("binaryArgument");
                source.Append("            uint ").Append(value)
                    .AppendLine(";")
                    .Append("            if (").Append(expression)
                    .AppendLine(".HasValue)")
                    .AppendLine("            {");
                var child = EmitBinaryWriteValue(
                    source,
                    generation,
                    OptionalBinaryPayloadType(parameter.BinaryType),
                    expression + ".Value!",
                    "                ");
                source.Append("                ").Append(value).Append(" = ")
                    .Append(child).AppendLine(";")
                    .AppendLine("            }")
                    .AppendLine("            else")
                    .AppendLine("            {")
                    .Append("                ").Append(value)
                    .AppendLine(" = writer.WriteUndefined();")
                    .AppendLine("            }");
            }
            else
            {
                value = EmitBinaryWriteValue(
                    source,
                    generation,
                    parameter.BinaryType,
                    expression,
                    "            ");
            }
            source.Append("            writer.SetArrayItem(root, ")
                .Append(index).Append(", ").Append(value).AppendLine(");");
        }
        source.AppendLine("            return root;")
            .AppendLine("        }")
            .AppendLine()
            .Append("        public static ").Append(resultType)
            .AppendLine(" DecodeResult(")
            .AppendLine("            global::WebScene.JavaScript.Interop.JavaScriptBinaryValue value,")
            .AppendLine("            global::WebScene.JavaScript.Interop.IJavaScriptInvoker invoker)")
            .AppendLine("        {")
            .Append("            return new ").Append(resultType)
            .AppendLine("(invoker, value.GetHandle());")
            .AppendLine("        }")
            .AppendLine("    }");
    }

}
