<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>False</IsPackable>
    <RootNamespace>wwwroot</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS8981</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="Avalonia.Desktop" />
    <!-- Ensure consistent CSS dependencies to avoid downgrade warnings -->
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="AngleSharp.Css" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WebScene\WebScene.csproj" />
  </ItemGroup>
</Project>
